import type { FinalChallenge } from "@/types";

export const javaFinalChallenges: Record<string, FinalChallenge> = {

  // ── Stranger Things ──────────────────────────────────────────────────────────
  "stranger-things-java": {
    id: "st-java-final",
    themeId: "stranger-things",
    languageId: "java",
    themedTitle: "The Hawkins Lab Java Trial",
    introNarrative:
      "Dr. Owens has mandated a Java certification for all Hawkins Lab staff. Five tests stand between you and clearance. The Mind Flayer cannot enter a well-typed program.",
    questions: [
      {
        id: "st-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Eleven's file needs to be created in the lab's Java database system before the mission can begin.",
        prompt: "In `class Main`, declare `String name = \"Eleven\"`, `int number = 11`, `boolean active = true`. Print all three using `System.out.println`.",
        hint: "Use `System.out.println(name)` for each variable.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String name = "Eleven";\n    int number = 11;\n    boolean active = true;\n    System.out.println(name);\n    System.out.println(number);\n    System.out.println(active);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String name = ___;\n    int number = ___;\n    boolean active = ___;\n    System.out.println(name);\n    System.out.println(number);\n    System.out.println(active);\n  }\n}`,
        testCases: [{ input: "", expected: "Eleven\n11\ntrue", description: "Prints name, number, active" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "st-java-final-2",
        concept: "Conditionals",
        narrative: "The Hawkins alarm system needs a threat level classifier. Lives depend on getting the conditions right.",
        prompt: "Write a static method `String threatLevel(int reading)` that returns `\"Critical\"` if >= 80, `\"High\"` if >= 50, else `\"Low\"`. Call it with 90, 60, and 20.",
        hint: "Use `if / else if / else` and `return` strings. Call the method from `main`.",
        solution: `public class Main {\n  static String threatLevel(int reading) {\n    if (reading >= 80) return "Critical";\n    else if (reading >= 50) return "High";\n    else return "Low";\n  }\n  public static void main(String[] args) {\n    System.out.println(threatLevel(90));\n    System.out.println(threatLevel(60));\n    System.out.println(threatLevel(20));\n  }\n}`,
        starterCode: `public class Main {\n  static String threatLevel(int reading) {\n    if (reading >= 80) return ___;\n    else if (reading >= 50) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(threatLevel(90));\n    System.out.println(threatLevel(60));\n    System.out.println(threatLevel(20));\n  }\n}`,
        testCases: [{ input: "90", expected: "Critical", description: "90 is Critical" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "st-java-final-3",
        concept: "Loops",
        narrative: "Dustin needs to print a numbered list of all Upside Down creatures for the party's battle plan.",
        prompt: "Create `String[] creatures = {\"Demogorgon\", \"Mind Flayer\", \"Demodog\", \"Vecna\"}`. Use a `for` loop to print each on a new line prefixed by its 1-based index, e.g. `1: Demogorgon`.",
        hint: "Use `for (int i = 0; i < creatures.length; i++)` and `System.out.println((i+1) + \": \" + creatures[i])`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String[] creatures = {"Demogorgon", "Mind Flayer", "Demodog", "Vecna"};\n    for (int i = 0; i < creatures.length; i++) {\n      System.out.println((i + 1) + ": " + creatures[i]);\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String[] creatures = {"Demogorgon", "Mind Flayer", "Demodog", "Vecna"};\n    for (int i = 0; i < creatures.length; i++) {\n      System.out.println((i + ___) + ": " + creatures[___]);\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "1: Demogorgon\n2: Mind Flayer\n3: Demodog\n4: Vecna", description: "Numbered creature list" }],
        conceptKeywords: ["for", "length", "System.out.println", "i"],
      },
      {
        id: "st-java-final-4",
        concept: "ArrayList",
        narrative: "Joyce is tracking sightings dynamically — new ones keep getting added as the Upside Down expands.",
        prompt: "Import and create `ArrayList<String> sightings`. Add `\"Demogorgon\"`, `\"Demodog\"`, `\"Mind Flayer\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;` at the top. Use `.add()` and `.size()`.",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> sightings = new ArrayList<>();\n    sightings.add("Demogorgon");\n    sightings.add("Demodog");\n    sightings.add("Mind Flayer");\n    System.out.println(sightings);\n    System.out.println(sightings.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> sightings = new ArrayList<>();\n    sightings.add(___);\n    sightings.add(___);\n    sightings.add(___);\n    System.out.println(sightings);\n    System.out.println(sightings.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Demogorgon, Demodog, Mind Flayer]\n3", description: "Sightings list and size" }],
        conceptKeywords: ["ArrayList", "add", "size", "import"],
      },
      {
        id: "st-java-final-5",
        concept: "HashMap",
        narrative: "Hopper maps each party member to their encounter count for the official Hawkins incident report.",
        prompt: "Import and create `HashMap<String, Integer> encounters`. Put `\"Mike\" -> 3`, `\"Dustin\" -> 7`, `\"Eleven\" -> 15`. Print Eleven's count and the total map size.",
        hint: "`import java.util.HashMap;` Use `.put()` and `.get()`.",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> encounters = new HashMap<>();\n    encounters.put("Mike", 3);\n    encounters.put("Dustin", 7);\n    encounters.put("Eleven", 15);\n    System.out.println(encounters.get("Eleven"));\n    System.out.println(encounters.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> encounters = new HashMap<>();\n    encounters.put("Mike", 3);\n    encounters.put("Dustin", 7);\n    encounters.put("Eleven", 15);\n    System.out.println(encounters.get(___));\n    System.out.println(encounters.size());\n  }\n}`,
        testCases: [{ input: "", expected: "15\n3", description: "Eleven's count and map size" }],
        conceptKeywords: ["HashMap", "put", "get", "import"],
      },
    ],
  },

  // ── Severance ────────────────────────────────────────────────────────────────
  "severance-java": {
    id: "sv-java-final",
    themeId: "severance",
    languageId: "java",
    themedTitle: "The Kier Compliance Test",
    introNarrative:
      "Lumon has mandated a Java skills assessment for all severed employees. The Board is watching. Complete the five tasks or face a formal Disciplinary Hearing. Mr. Milchick will be grading.",
    questions: [
      {
        id: "sv-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Helly's Lumon profile needs to be initialised in the Java system before refinement quota can be assigned.",
        prompt: "Declare `String employee = \"Helly R\"`, `int quota = 100`, `boolean compliant = false`. Print all three.",
        hint: "Java booleans are lowercase: `true` and `false`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String employee = "Helly R";\n    int quota = 100;\n    boolean compliant = false;\n    System.out.println(employee);\n    System.out.println(quota);\n    System.out.println(compliant);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String employee = ___;\n    int quota = ___;\n    boolean compliant = ___;\n    System.out.println(employee);\n    System.out.println(quota);\n    System.out.println(compliant);\n  }\n}`,
        testCases: [{ input: "", expected: "Helly R\n100\nfalse", description: "Employee profile printed" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "sv-java-final-2",
        concept: "Conditionals",
        narrative: "The quota system classifies each employee's performance tier based on their refinement score.",
        prompt: "Write `static String tier(int score)` returning `\"Exceeds\"` if score >= 90, `\"Meets\"` if >= 60, else `\"Below\"`. Call it with 95, 70, 40.",
        hint: "Use chained `if / else if / else` with `return`.",
        solution: `public class Main {\n  static String tier(int score) {\n    if (score >= 90) return "Exceeds";\n    else if (score >= 60) return "Meets";\n    else return "Below";\n  }\n  public static void main(String[] args) {\n    System.out.println(tier(95));\n    System.out.println(tier(70));\n    System.out.println(tier(40));\n  }\n}`,
        starterCode: `public class Main {\n  static String tier(int score) {\n    if (score >= 90) return ___;\n    else if (score >= 60) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(tier(95));\n    System.out.println(tier(70));\n    System.out.println(tier(40));\n  }\n}`,
        testCases: [{ input: "95", expected: "Exceeds", description: "95 exceeds quota" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "sv-java-final-3",
        concept: "Loops",
        narrative: "Milchick needs to print the MDR team's bin assignments for the morning briefing.",
        prompt: "Create `String[] bins = {\"Bin A\", \"Bin B\", \"Bin C\", \"Bin D\"}`. Use a `for` loop with `for (String bin : bins)` to print each.",
        hint: "Enhanced for-each loop: `for (String bin : bins) { System.out.println(bin); }`",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String[] bins = {"Bin A", "Bin B", "Bin C", "Bin D"};\n    for (String bin : bins) {\n      System.out.println(bin);\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String[] bins = {"Bin A", "Bin B", "Bin C", "Bin D"};\n    for (String ___ : bins) {\n      System.out.println(___);\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "Bin A\nBin B\nBin C\nBin D", description: "All bins printed" }],
        conceptKeywords: ["for", "String", "System.out.println"],
      },
      {
        id: "sv-java-final-4",
        concept: "ArrayList",
        narrative: "The MDR team roster keeps changing as employees are added — an ArrayList handles the dynamic list.",
        prompt: "Create `ArrayList<String> mdr`. Add `\"Mark\"`, `\"Helly\"`, `\"Irving\"`, `\"Dylan\"`. Print the list and its size.",
        hint: "Don't forget `import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> mdr = new ArrayList<>();\n    mdr.add("Mark");\n    mdr.add("Helly");\n    mdr.add("Irving");\n    mdr.add("Dylan");\n    System.out.println(mdr);\n    System.out.println(mdr.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> mdr = new ArrayList<>();\n    mdr.add(___);\n    mdr.add(___);\n    mdr.add(___);\n    mdr.add(___);\n    System.out.println(mdr);\n    System.out.println(mdr.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Mark, Helly, Irving, Dylan]\n4", description: "MDR roster and size" }],
        conceptKeywords: ["ArrayList", "add", "size", "import"],
      },
      {
        id: "sv-java-final-5",
        concept: "HashMap",
        narrative: "The Board wants individual quota completion rates per employee mapped for the annual audit.",
        prompt: "Create `HashMap<String, Integer> quotas`. Put `\"Mark\" -> 88`, `\"Helly\" -> 74`, `\"Irving\" -> 95`. Print Mark's score and the total entries.",
        hint: "`import java.util.HashMap;` then `.put()` and `.get(\"Mark\")`.",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> quotas = new HashMap<>();\n    quotas.put("Mark", 88);\n    quotas.put("Helly", 74);\n    quotas.put("Irving", 95);\n    System.out.println(quotas.get("Mark"));\n    System.out.println(quotas.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> quotas = new HashMap<>();\n    quotas.put("Mark", 88);\n    quotas.put("Helly", 74);\n    quotas.put("Irving", 95);\n    System.out.println(quotas.get(___));\n    System.out.println(quotas.size());\n  }\n}`,
        testCases: [{ input: "", expected: "88\n3", description: "Mark's score and total entries" }],
        conceptKeywords: ["HashMap", "put", "get", "import"],
      },
    ],
  },

  // ── Breaking Bad ─────────────────────────────────────────────────────────────
  "breaking-bad-java": {
    id: "bb-java-final",
    themeId: "breaking-bad",
    languageId: "java",
    themedTitle: "The Heisenberg Test",
    introNarrative:
      "I am the one who types. Walter White has set five Java challenges. Pass them all and the blue product reaches distribution. Fail and you're off the team.",
    questions: [
      {
        id: "bb-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Walter needs to initialise the batch record in the lab's Java tracking system.",
        prompt: "Declare `String product = \"Blue Sky\"`, `double purity = 99.1`, `boolean distributed = false`. Print all three.",
        hint: "Use `double` for decimal numbers. Java booleans are lowercase.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String product = "Blue Sky";\n    double purity = 99.1;\n    boolean distributed = false;\n    System.out.println(product);\n    System.out.println(purity);\n    System.out.println(distributed);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String product = ___;\n    double purity = ___;\n    boolean distributed = ___;\n    System.out.println(product);\n    System.out.println(purity);\n    System.out.println(distributed);\n  }\n}`,
        testCases: [{ input: "", expected: "Blue Sky\n99.1\nfalse", description: "Batch record printed" }],
        conceptKeywords: ["String", "double", "boolean", "System.out.println"],
      },
      {
        id: "bb-java-final-2",
        concept: "Conditionals",
        narrative: "Walter's quality control system classifies each batch based on purity percentage.",
        prompt: "Write `static String grade(double purity)` returning `\"Premium\"` if >= 99, `\"Standard\"` if >= 90, else `\"Reject\"`. Call with 99.1, 94.5, 85.0.",
        hint: "Chain `if / else if / else` and `return` strings.",
        solution: `public class Main {\n  static String grade(double purity) {\n    if (purity >= 99) return "Premium";\n    else if (purity >= 90) return "Standard";\n    else return "Reject";\n  }\n  public static void main(String[] args) {\n    System.out.println(grade(99.1));\n    System.out.println(grade(94.5));\n    System.out.println(grade(85.0));\n  }\n}`,
        starterCode: `public class Main {\n  static String grade(double purity) {\n    if (purity >= 99) return ___;\n    else if (purity >= 90) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(grade(99.1));\n    System.out.println(grade(94.5));\n    System.out.println(grade(85.0));\n  }\n}`,
        testCases: [{ input: "99.1", expected: "Premium", description: "99.1% is Premium" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "bb-java-final-3",
        concept: "Loops",
        narrative: "Jesse tracks earnings from each cook with a running total he logs batch by batch.",
        prompt: "Create `int[] batches = {5000, 12000, 8500, 21000, 9000}`. Use a `for` loop to sum the values and print the total after the loop.",
        hint: "Declare `int total = 0;` before the loop. Add each element inside.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    int[] batches = {5000, 12000, 8500, 21000, 9000};\n    int total = 0;\n    for (int b : batches) {\n      total += b;\n    }\n    System.out.println(total);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    int[] batches = {5000, 12000, 8500, 21000, 9000};\n    int total = 0;\n    for (int b : batches) {\n      total += ___;\n    }\n    System.out.println(total);\n  }\n}`,
        testCases: [{ input: "", expected: "55500", description: "Total batch earnings" }],
        conceptKeywords: ["for", "total", "+=", "System.out.println"],
      },
      {
        id: "bb-java-final-4",
        concept: "ArrayList",
        narrative: "Saul's shell company registry needs a dynamic list of business names that can grow.",
        prompt: "Create `ArrayList<String> companies`. Add `\"A1A Car Wash\"`, `\"Los Pollos Hermanos\"`, `\"Madrigal\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> companies = new ArrayList<>();\n    companies.add("A1A Car Wash");\n    companies.add("Los Pollos Hermanos");\n    companies.add("Madrigal");\n    System.out.println(companies);\n    System.out.println(companies.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> companies = new ArrayList<>();\n    companies.add(___);\n    companies.add(___);\n    companies.add(___);\n    System.out.println(companies);\n    System.out.println(companies.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[A1A Car Wash, Los Pollos Hermanos, Madrigal]\n3", description: "Shell company list and size" }],
        conceptKeywords: ["ArrayList", "add", "size", "import"],
      },
      {
        id: "bb-java-final-5",
        concept: "HashMap",
        narrative: "Skyler maps each cartel contact to their known territory for the DEA's benefit.",
        prompt: "Create `HashMap<String, String> territories`. Put `\"Heisenberg\" -> \"Albuquerque\"`, `\"Gus\" -> \"Southwest\"`, `\"Cartel\" -> \"Mexico\"`. Print Gus's territory and the map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> territories = new HashMap<>();\n    territories.put("Heisenberg", "Albuquerque");\n    territories.put("Gus", "Southwest");\n    territories.put("Cartel", "Mexico");\n    System.out.println(territories.get("Gus"));\n    System.out.println(territories.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> territories = new HashMap<>();\n    territories.put("Heisenberg", "Albuquerque");\n    territories.put("Gus", "Southwest");\n    territories.put("Cartel", "Mexico");\n    System.out.println(territories.get(___));\n    System.out.println(territories.size());\n  }\n}`,
        testCases: [{ input: "", expected: "Southwest\n3", description: "Gus's territory and map size" }],
        conceptKeywords: ["HashMap", "put", "get", "import"],
      },
    ],
  },

  // ── The Office ───────────────────────────────────────────────────────────────
  "the-office-java": {
    id: "to-java-final",
    themeId: "the-office",
    languageId: "java",
    themedTitle: "The Dundies Java Final",
    introNarrative:
      "Michael Scott has declared the Dundies will now include a Java programming award. Dwight has been appointed Chief Java Officer. Five challenges. Winners get a Dundie. Losers get a mandatory sensitivity training session.",
    questions: [
      {
        id: "to-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Michael needs to enter Dunder Mifflin Scranton's official stats into the company's Java ERP system.",
        prompt: "Declare `String branch = \"Scranton\"`, `int employees = 15`, `double salesTarget = 500000.0`. Print all three.",
        hint: "Use `double` for the sales target decimal.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String branch = "Scranton";\n    int employees = 15;\n    double salesTarget = 500000.0;\n    System.out.println(branch);\n    System.out.println(employees);\n    System.out.println(salesTarget);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String branch = ___;\n    int employees = ___;\n    double salesTarget = ___;\n    System.out.println(branch);\n    System.out.println(employees);\n    System.out.println(salesTarget);\n  }\n}`,
        testCases: [{ input: "", expected: "Scranton\n15\n500000.0", description: "Branch stats printed" }],
        conceptKeywords: ["String", "int", "double", "System.out.println"],
      },
      {
        id: "to-java-final-2",
        concept: "Conditionals",
        narrative: "Dwight's threat evaluation system rates employees on a scale and assigns a threat level.",
        prompt: "Write `static String threatAssessment(int score)` returning `\"Threat\"` if >= 8, `\"Neutral\"` if >= 5, else `\"Harmless\"`. Call with 9, 6, 2.",
        hint: "Chained if/else if/else with return.",
        solution: `public class Main {\n  static String threatAssessment(int score) {\n    if (score >= 8) return "Threat";\n    else if (score >= 5) return "Neutral";\n    else return "Harmless";\n  }\n  public static void main(String[] args) {\n    System.out.println(threatAssessment(9));\n    System.out.println(threatAssessment(6));\n    System.out.println(threatAssessment(2));\n  }\n}`,
        starterCode: `public class Main {\n  static String threatAssessment(int score) {\n    if (score >= 8) return ___;\n    else if (score >= 5) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(threatAssessment(9));\n    System.out.println(threatAssessment(6));\n    System.out.println(threatAssessment(2));\n  }\n}`,
        testCases: [{ input: "9", expected: "Threat", description: "Score 9 is a Threat" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "to-java-final-3",
        concept: "Loops",
        narrative: "Kevin is totalling up the monthly sales figures across all quarters for the annual report.",
        prompt: "Create `int[] quarterly = {42000, 38000, 51000, 47000}`. Sum them in a loop and print the total.",
        hint: "Declare `int total = 0;` outside, add inside the loop.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    int[] quarterly = {42000, 38000, 51000, 47000};\n    int total = 0;\n    for (int q : quarterly) {\n      total += q;\n    }\n    System.out.println(total);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    int[] quarterly = {42000, 38000, 51000, 47000};\n    int total = 0;\n    for (int q : quarterly) {\n      total += ___;\n    }\n    System.out.println(total);\n  }\n}`,
        testCases: [{ input: "", expected: "178000", description: "Total quarterly sales" }],
        conceptKeywords: ["for", "total", "+="],
      },
      {
        id: "to-java-final-4",
        concept: "ArrayList",
        narrative: "Pam is building the party planning committee's dynamic guest list — it grows every time someone mentions 'free food'.",
        prompt: "Create `ArrayList<String> guests`. Add `\"Michael\"`, `\"Dwight\"`, `\"Jim\"`, `\"Pam\"`. Remove `\"Dwight\"` (he's on patrol). Print the list and its size.",
        hint: "Use `.remove(\"Dwight\")` to remove by value.",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> guests = new ArrayList<>();\n    guests.add("Michael");\n    guests.add("Dwight");\n    guests.add("Jim");\n    guests.add("Pam");\n    guests.remove("Dwight");\n    System.out.println(guests);\n    System.out.println(guests.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> guests = new ArrayList<>();\n    guests.add("Michael");\n    guests.add("Dwight");\n    guests.add("Jim");\n    guests.add("Pam");\n    guests.remove(___);\n    System.out.println(guests);\n    System.out.println(guests.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Michael, Jim, Pam]\n3", description: "Guest list without Dwight" }],
        conceptKeywords: ["ArrayList", "add", "remove", "size"],
      },
      {
        id: "to-java-final-5",
        concept: "HashMap",
        narrative: "Jim is tracking how many sales calls each rep made this week for the leaderboard.",
        prompt: "Create `HashMap<String, Integer> calls`. Put `\"Jim\" -> 42`, `\"Dwight\" -> 67`, `\"Andy\" -> 31`. Print Dwight's count and the map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> calls = new HashMap<>();\n    calls.put("Jim", 42);\n    calls.put("Dwight", 67);\n    calls.put("Andy", 31);\n    System.out.println(calls.get("Dwight"));\n    System.out.println(calls.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> calls = new HashMap<>();\n    calls.put("Jim", 42);\n    calls.put("Dwight", 67);\n    calls.put("Andy", 31);\n    System.out.println(calls.get(___));\n    System.out.println(calls.size());\n  }\n}`,
        testCases: [{ input: "", expected: "67\n3", description: "Dwight's calls and map size" }],
        conceptKeywords: ["HashMap", "put", "get", "import"],
      },
    ],
  },

  // ── Game of Thrones ──────────────────────────────────────────────────────────
  "game-of-thrones-java": {
    id: "got-java-final",
    themeId: "game-of-thrones",
    languageId: "java",
    themedTitle: "The Iron Throne Exam",
    introNarrative:
      "You know nothing, Jon Snow — not yet. Five Java trials stand between you and the throne. The Maester has set the tests. The realm watches.",
    questions: [
      {
        id: "got-java-final-1",
        concept: "Variables & Data Types",
        narrative: "The Citadel needs Jon's official record entered before he can be recognised as a leader.",
        prompt: "Declare `String name = \"Jon Snow\"`, `int swords = 1000`, `boolean knowsNothing = true`. Print all three.",
        hint: "Standard Java variable declarations.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String name = "Jon Snow";\n    int swords = 1000;\n    boolean knowsNothing = true;\n    System.out.println(name);\n    System.out.println(swords);\n    System.out.println(knowsNothing);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String name = ___;\n    int swords = ___;\n    boolean knowsNothing = ___;\n    System.out.println(name);\n    System.out.println(swords);\n    System.out.println(knowsNothing);\n  }\n}`,
        testCases: [{ input: "", expected: "Jon Snow\n1000\ntrue", description: "Jon's record printed" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "got-java-final-2",
        concept: "Conditionals",
        narrative: "The Small Council must classify each army's strength to determine alliances.",
        prompt: "Write `static String armyClass(int size)` returning `\"Unstoppable\"` if size >= 100000, `\"Formidable\"` if >= 50000, else `\"Small band\"`. Call with 150000, 60000, 20000.",
        hint: "Chain if/else if/else returning string literals.",
        solution: `public class Main {\n  static String armyClass(int size) {\n    if (size >= 100000) return "Unstoppable";\n    else if (size >= 50000) return "Formidable";\n    else return "Small band";\n  }\n  public static void main(String[] args) {\n    System.out.println(armyClass(150000));\n    System.out.println(armyClass(60000));\n    System.out.println(armyClass(20000));\n  }\n}`,
        starterCode: `public class Main {\n  static String armyClass(int size) {\n    if (size >= 100000) return ___;\n    else if (size >= 50000) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(armyClass(150000));\n    System.out.println(armyClass(60000));\n    System.out.println(armyClass(20000));\n  }\n}`,
        testCases: [{ input: "150000", expected: "Unstoppable", description: "Large army is Unstoppable" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "got-java-final-3",
        concept: "Loops",
        narrative: "The Master of Coin must tally tribute payments from all seven kingdoms.",
        prompt: "Create `int[] tributes = {12000, 8500, 21000, 4000, 16500, 9000, 7200}`. Sum them with a loop and print the total.",
        hint: "For-each loop over the array, accumulate into `total`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    int[] tributes = {12000, 8500, 21000, 4000, 16500, 9000, 7200};\n    int total = 0;\n    for (int t : tributes) total += t;\n    System.out.println(total);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    int[] tributes = {12000, 8500, 21000, 4000, 16500, 9000, 7200};\n    int total = 0;\n    for (int t : tributes) total += ___;\n    System.out.println(total);\n  }\n}`,
        testCases: [{ input: "", expected: "78200", description: "Total tributes from all kingdoms" }],
        conceptKeywords: ["for", "total", "+="],
      },
      {
        id: "got-java-final-4",
        concept: "ArrayList",
        narrative: "Daenerys tracks her dragons dynamically — new ones might hatch.",
        prompt: "Create `ArrayList<String> dragons`. Add `\"Drogon\"`, `\"Rhaegal\"`, `\"Viserion\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> dragons = new ArrayList<>();\n    dragons.add("Drogon");\n    dragons.add("Rhaegal");\n    dragons.add("Viserion");\n    System.out.println(dragons);\n    System.out.println(dragons.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> dragons = new ArrayList<>();\n    dragons.add(___);\n    dragons.add(___);\n    dragons.add(___);\n    System.out.println(dragons);\n    System.out.println(dragons.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Drogon, Rhaegal, Viserion]\n3", description: "Dragon roster" }],
        conceptKeywords: ["ArrayList", "add", "size"],
      },
      {
        id: "got-java-final-5",
        concept: "HashMap",
        narrative: "The raven network maps each castle to its current lord for fast dispatch.",
        prompt: "Create `HashMap<String, String> lords`. Put `\"Winterfell\" -> \"Jon Snow\"`, `\"Casterly Rock\" -> \"Tyrion Lannister\"`, `\"Dragonstone\" -> \"Daenerys\"`. Print Winterfell's lord and map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> lords = new HashMap<>();\n    lords.put("Winterfell", "Jon Snow");\n    lords.put("Casterly Rock", "Tyrion Lannister");\n    lords.put("Dragonstone", "Daenerys");\n    System.out.println(lords.get("Winterfell"));\n    System.out.println(lords.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> lords = new HashMap<>();\n    lords.put("Winterfell", "Jon Snow");\n    lords.put("Casterly Rock", "Tyrion Lannister");\n    lords.put("Dragonstone", "Daenerys");\n    System.out.println(lords.get(___));\n    System.out.println(lords.size());\n  }\n}`,
        testCases: [{ input: "", expected: "Jon Snow\n3", description: "Winterfell's lord and map size" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── The Matrix ───────────────────────────────────────────────────────────────
  "the-matrix-java": {
    id: "mx-java-final",
    themeId: "the-matrix",
    languageId: "java",
    themedTitle: "The Red Pill Gauntlet",
    introNarrative:
      "You took the red pill. Now prove your mind is free. The Architect has programmed five Java challenges to test those who claim to see beyond the simulation.",
    questions: [
      {
        id: "mx-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Neo's anomaly file needs to be created in the Matrix system before Agent Smith can track him.",
        prompt: "Declare `String name = \"Neo\"`, `boolean awakened = true`, `int anomalyLevel = 6`. Print all three.",
        hint: "Standard declarations — boolean is lowercase in Java.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String name = "Neo";\n    boolean awakened = true;\n    int anomalyLevel = 6;\n    System.out.println(name);\n    System.out.println(awakened);\n    System.out.println(anomalyLevel);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String name = ___;\n    boolean awakened = ___;\n    int anomalyLevel = ___;\n    System.out.println(name);\n    System.out.println(awakened);\n    System.out.println(anomalyLevel);\n  }\n}`,
        testCases: [{ input: "", expected: "Neo\ntrue\n6", description: "Neo's anomaly file" }],
        conceptKeywords: ["String", "boolean", "int", "System.out.println"],
      },
      {
        id: "mx-java-final-2",
        concept: "Conditionals",
        narrative: "The Oracle predicts outcomes based on the anomaly's frequency score.",
        prompt: "Write `static String predict(int freq)` returning `\"The One\"` if freq >= 6, `\"Potential\"` if >= 3, else `\"Ordinary\"`. Call with 7, 4, 1.",
        hint: "Chained if/else if/else.",
        solution: `public class Main {\n  static String predict(int freq) {\n    if (freq >= 6) return "The One";\n    else if (freq >= 3) return "Potential";\n    else return "Ordinary";\n  }\n  public static void main(String[] args) {\n    System.out.println(predict(7));\n    System.out.println(predict(4));\n    System.out.println(predict(1));\n  }\n}`,
        starterCode: `public class Main {\n  static String predict(int freq) {\n    if (freq >= 6) return ___;\n    else if (freq >= 3) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(predict(7));\n    System.out.println(predict(4));\n    System.out.println(predict(1));\n  }\n}`,
        testCases: [{ input: "7", expected: "The One", description: "Freq 7 is The One" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "mx-java-final-3",
        concept: "Loops",
        narrative: "Tank is iterating through the resistance's training scores to find the cumulative total.",
        prompt: "Create `int[] scores = {85, 92, 78, 95, 88}`. Sum them with a loop. Print the total.",
        hint: "For-each loop accumulating into `int total = 0`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    int[] scores = {85, 92, 78, 95, 88};\n    int total = 0;\n    for (int s : scores) total += s;\n    System.out.println(total);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    int[] scores = {85, 92, 78, 95, 88};\n    int total = 0;\n    for (int s : scores) total += ___;\n    System.out.println(total);\n  }\n}`,
        testCases: [{ input: "", expected: "438", description: "Sum of training scores" }],
        conceptKeywords: ["for", "total", "+="],
      },
      {
        id: "mx-java-final-4",
        concept: "ArrayList",
        narrative: "Morpheus maintains a dynamic list of freed minds — it grows every time someone takes the red pill.",
        prompt: "Create `ArrayList<String> freed`. Add `\"Neo\"`, `\"Trinity\"`, `\"Tank\"`, `\"Dozer\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> freed = new ArrayList<>();\n    freed.add("Neo");\n    freed.add("Trinity");\n    freed.add("Tank");\n    freed.add("Dozer");\n    System.out.println(freed);\n    System.out.println(freed.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> freed = new ArrayList<>();\n    freed.add(___);\n    freed.add(___);\n    freed.add(___);\n    freed.add(___);\n    System.out.println(freed);\n    System.out.println(freed.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Neo, Trinity, Tank, Dozer]\n4", description: "Freed minds list" }],
        conceptKeywords: ["ArrayList", "add", "size"],
      },
      {
        id: "mx-java-final-5",
        concept: "HashMap",
        narrative: "The Operator maps each operative to their specialist skill for mission assignment.",
        prompt: "Create `HashMap<String, String> skills`. Put `\"Neo\" -> \"Combat\"`, `\"Trinity\" -> \"Hacking\"`, `\"Morpheus\" -> \"Leadership\"`. Print Neo's skill and map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> skills = new HashMap<>();\n    skills.put("Neo", "Combat");\n    skills.put("Trinity", "Hacking");\n    skills.put("Morpheus", "Leadership");\n    System.out.println(skills.get("Neo"));\n    System.out.println(skills.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> skills = new HashMap<>();\n    skills.put("Neo", "Combat");\n    skills.put("Trinity", "Hacking");\n    skills.put("Morpheus", "Leadership");\n    System.out.println(skills.get(___));\n    System.out.println(skills.size());\n  }\n}`,
        testCases: [{ input: "", expected: "Combat\n3", description: "Neo's skill and map size" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── Rick and Morty ───────────────────────────────────────────────────────────
  "rick-and-morty-java": {
    id: "rm-java-final",
    themeId: "rick-and-morty",
    languageId: "java",
    themedTitle: "Rick's Java Certification",
    introNarrative:
      "Rick has *burp* upgraded his portal gun to require Java certification. Five tests, Morty. If you pass, we go to Blips and Chitz. If you don't, you're getting a Meeseeks box for your birthday.",
    questions: [
      {
        id: "rm-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Rick needs to log C-137's portal gun specs into the interdimensional registry.",
        prompt: "Declare `String owner = \"Rick Sanchez\"`, `int iq = 312`, `boolean charged = true`. Print all three.",
        hint: "Java boolean: lowercase `true`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String owner = "Rick Sanchez";\n    int iq = 312;\n    boolean charged = true;\n    System.out.println(owner);\n    System.out.println(iq);\n    System.out.println(charged);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String owner = ___;\n    int iq = ___;\n    boolean charged = ___;\n    System.out.println(owner);\n    System.out.println(iq);\n    System.out.println(charged);\n  }\n}`,
        testCases: [{ input: "", expected: "Rick Sanchez\n312\ntrue", description: "Portal gun registry entry" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "rm-java-final-2",
        concept: "Conditionals",
        narrative: "The Citadel of Ricks ranks each Rick by IQ tier to determine their council privileges.",
        prompt: "Write `static String rankRick(int iq)` returning `\"Genius\"` if iq >= 300, `\"Smart\"` if >= 200, else `\"Jerry-level\"`. Call with 312, 220, 150.",
        hint: "Chain if/else if/else returning the three labels.",
        solution: `public class Main {\n  static String rankRick(int iq) {\n    if (iq >= 300) return "Genius";\n    else if (iq >= 200) return "Smart";\n    else return "Jerry-level";\n  }\n  public static void main(String[] args) {\n    System.out.println(rankRick(312));\n    System.out.println(rankRick(220));\n    System.out.println(rankRick(150));\n  }\n}`,
        starterCode: `public class Main {\n  static String rankRick(int iq) {\n    if (iq >= 300) return ___;\n    else if (iq >= 200) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(rankRick(312));\n    System.out.println(rankRick(220));\n    System.out.println(rankRick(150));\n  }\n}`,
        testCases: [{ input: "312", expected: "Genius", description: "IQ 312 is Genius" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "rm-java-final-3",
        concept: "Loops",
        narrative: "Morty needs to log each adventure number to his journal before Rick erases his memories again.",
        prompt: "Use a `for` loop to print numbers 1 through 5, each on a new line formatted as `\"Adventure #N\"`.",
        hint: "`for (int i = 1; i <= 5; i++)` then `System.out.println(\"Adventure #\" + i)`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= 5; i++) {\n      System.out.println("Adventure #" + i);\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= ___; i++) {\n      System.out.println("Adventure #" + ___);\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "Adventure #1\nAdventure #2\nAdventure #3\nAdventure #4\nAdventure #5", description: "Five adventure entries" }],
        conceptKeywords: ["for", "i++", "System.out.println"],
      },
      {
        id: "rm-java-final-4",
        concept: "ArrayList",
        narrative: "Rick's portal directory dynamically tracks every dimension he's visited.",
        prompt: "Create `ArrayList<String> dimensions`. Add `\"C-137\"`, `\"Cronenberg World\"`, `\"Evil Rick's dimension\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> dimensions = new ArrayList<>();\n    dimensions.add("C-137");\n    dimensions.add("Cronenberg World");\n    dimensions.add("Evil Rick's dimension");\n    System.out.println(dimensions);\n    System.out.println(dimensions.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> dimensions = new ArrayList<>();\n    dimensions.add(___);\n    dimensions.add(___);\n    dimensions.add(___);\n    System.out.println(dimensions);\n    System.out.println(dimensions.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[C-137, Cronenberg World, Evil Rick's dimension]\n3", description: "Visited dimensions" }],
        conceptKeywords: ["ArrayList", "add", "size"],
      },
      {
        id: "rm-java-final-5",
        concept: "HashMap",
        narrative: "Rick maps each Morty to their dimension number for the Citadel's records.",
        prompt: "Create `HashMap<String, String>`. Put `\"Primary Morty\" -> \"C-137\"`, `\"Evil Morty\" -> \"Unknown\"`, `\"Doofus Morty\" -> \"J19Z7\"`. Print Primary Morty's dimension and size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> mortys = new HashMap<>();\n    mortys.put("Primary Morty", "C-137");\n    mortys.put("Evil Morty", "Unknown");\n    mortys.put("Doofus Morty", "J19Z7");\n    System.out.println(mortys.get("Primary Morty"));\n    System.out.println(mortys.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> mortys = new HashMap<>();\n    mortys.put("Primary Morty", "C-137");\n    mortys.put("Evil Morty", "Unknown");\n    mortys.put("Doofus Morty", "J19Z7");\n    System.out.println(mortys.get(___));\n    System.out.println(mortys.size());\n  }\n}`,
        testCases: [{ input: "", expected: "C-137\n3", description: "Primary Morty's dimension" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── Squid Game ───────────────────────────────────────────────────────────────
  "squid-game-java": {
    id: "sg-java-final",
    themeId: "squid-game",
    languageId: "java",
    themedTitle: "The Glass Bridge Java Challenge",
    introNarrative:
      "The games have ended. But the Front Man has one final challenge — not of survival, but of skill. Five Java problems stand between you and the 45.6 billion won prize.",
    questions: [
      {
        id: "sg-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Player 456 needs to register his credentials in the final game's computer system.",
        prompt: "Declare `String playerName = \"Seong Gi-hun\"`, `int number = 456`, `boolean survived = true`. Print all three.",
        hint: "Standard Java declarations — boolean is lowercase.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String playerName = "Seong Gi-hun";\n    int number = 456;\n    boolean survived = true;\n    System.out.println(playerName);\n    System.out.println(number);\n    System.out.println(survived);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String playerName = ___;\n    int number = ___;\n    boolean survived = ___;\n    System.out.println(playerName);\n    System.out.println(number);\n    System.out.println(survived);\n  }\n}`,
        testCases: [{ input: "", expected: "Seong Gi-hun\n456\ntrue", description: "Player 456 registration" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "sg-java-final-2",
        concept: "Conditionals",
        narrative: "The game's elimination system classifies each player's debt level to determine their motivation.",
        prompt: "Write `static String debtClass(long debt)` returning `\"Critical\"` if debt >= 100000000, `\"High\"` if >= 50000000, else `\"Manageable\"`. Call with 160000000, 60000000, 20000000.",
        hint: "Use `long` type for large numbers. Chain if/else if/else.",
        solution: `public class Main {\n  static String debtClass(long debt) {\n    if (debt >= 100000000) return "Critical";\n    else if (debt >= 50000000) return "High";\n    else return "Manageable";\n  }\n  public static void main(String[] args) {\n    System.out.println(debtClass(160000000));\n    System.out.println(debtClass(60000000));\n    System.out.println(debtClass(20000000));\n  }\n}`,
        starterCode: `public class Main {\n  static String debtClass(long debt) {\n    if (debt >= 100000000) return ___;\n    else if (debt >= 50000000) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(debtClass(160000000));\n    System.out.println(debtClass(60000000));\n    System.out.println(debtClass(20000000));\n  }\n}`,
        testCases: [{ input: "160000000", expected: "Critical", description: "160M debt is Critical" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "sg-java-final-3",
        concept: "Loops",
        narrative: "The guard calls out each game number before it begins. Generate the game announcements.",
        prompt: "Use a `for` loop to print `\"Game N begins\"` for N from 1 to 6.",
        hint: "`for (int i = 1; i <= 6; i++)` with `System.out.println(\"Game \" + i + \" begins\")`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= 6; i++) {\n      System.out.println("Game " + i + " begins");\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= ___; i++) {\n      System.out.println("Game " + ___ + " begins");\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "Game 1 begins\nGame 2 begins\nGame 3 begins\nGame 4 begins\nGame 5 begins\nGame 6 begins", description: "Six game announcements" }],
        conceptKeywords: ["for", "i++", "System.out.println"],
      },
      {
        id: "sg-java-final-4",
        concept: "ArrayList",
        narrative: "The Front Man dynamically tracks which players remain after each elimination round.",
        prompt: "Create `ArrayList<Integer> survivors`. Add player numbers 456, 67, 218. Remove 218 (he was eliminated). Print the list and size.",
        hint: "Use `ArrayList<Integer>` and `.remove(Integer.valueOf(218))` to remove by value.",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<Integer> survivors = new ArrayList<>();\n    survivors.add(456);\n    survivors.add(67);\n    survivors.add(218);\n    survivors.remove(Integer.valueOf(218));\n    System.out.println(survivors);\n    System.out.println(survivors.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<Integer> survivors = new ArrayList<>();\n    survivors.add(456);\n    survivors.add(67);\n    survivors.add(218);\n    survivors.remove(Integer.valueOf(___));\n    System.out.println(survivors);\n    System.out.println(survivors.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[456, 67]\n2", description: "Survivors after eliminating 218" }],
        conceptKeywords: ["ArrayList", "add", "remove", "Integer.valueOf"],
      },
      {
        id: "sg-java-final-5",
        concept: "HashMap",
        narrative: "The VIP observers want a map of each game name to the number of eliminations.",
        prompt: "Create `HashMap<String, Integer> eliminations`. Put `\"Red Light Green Light\" -> 201`, `\"Honeycomb\" -> 80`, `\"Tug of War\" -> 100`. Print Honeycomb's count and map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> eliminations = new HashMap<>();\n    eliminations.put("Red Light Green Light", 201);\n    eliminations.put("Honeycomb", 80);\n    eliminations.put("Tug of War", 100);\n    System.out.println(eliminations.get("Honeycomb"));\n    System.out.println(eliminations.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> eliminations = new HashMap<>();\n    eliminations.put("Red Light Green Light", 201);\n    eliminations.put("Honeycomb", 80);\n    eliminations.put("Tug of War", 100);\n    System.out.println(eliminations.get(___));\n    System.out.println(eliminations.size());\n  }\n}`,
        testCases: [{ input: "", expected: "80\n3", description: "Honeycomb eliminations and map size" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── Arrested Development ─────────────────────────────────────────────────────
  "arrested-development-java": {
    id: "ad-java-final",
    themeId: "arrested-development",
    languageId: "java",
    themedTitle: "The Bluth Company Java Audit",
    introNarrative:
      "The SEC is auditing the Bluth Company — again. Michael needs someone fluent in Java to prove the books are legitimate. There's always money in passing this exam.",
    questions: [
      {
        id: "ad-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Michael needs the banana stand's financials entered into the Java accounting system.",
        prompt: "Declare `String asset = \"Banana Stand\"`, `int hiddenCash = 250000`, `boolean profitable = true`. Print all three.",
        hint: "Java boolean is lowercase `true`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String asset = "Banana Stand";\n    int hiddenCash = 250000;\n    boolean profitable = true;\n    System.out.println(asset);\n    System.out.println(hiddenCash);\n    System.out.println(profitable);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String asset = ___;\n    int hiddenCash = ___;\n    boolean profitable = ___;\n    System.out.println(asset);\n    System.out.println(hiddenCash);\n    System.out.println(profitable);\n  }\n}`,
        testCases: [{ input: "", expected: "Banana Stand\n250000\ntrue", description: "Banana stand financials" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "ad-java-final-2",
        concept: "Conditionals",
        narrative: "Gob's illusion booking system rates each show's revenue to decide if it's worth scheduling.",
        prompt: "Write `static String illusionRating(int revenue)` returning `\"Headline\"` if revenue >= 20000, `\"Support\"` if >= 5000, else `\"Free show\"`. Call with 25000, 8000, 1000.",
        hint: "Chain if/else if/else.",
        solution: `public class Main {\n  static String illusionRating(int revenue) {\n    if (revenue >= 20000) return "Headline";\n    else if (revenue >= 5000) return "Support";\n    else return "Free show";\n  }\n  public static void main(String[] args) {\n    System.out.println(illusionRating(25000));\n    System.out.println(illusionRating(8000));\n    System.out.println(illusionRating(1000));\n  }\n}`,
        starterCode: `public class Main {\n  static String illusionRating(int revenue) {\n    if (revenue >= 20000) return ___;\n    else if (revenue >= 5000) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(illusionRating(25000));\n    System.out.println(illusionRating(8000));\n    System.out.println(illusionRating(1000));\n  }\n}`,
        testCases: [{ input: "25000", expected: "Headline", description: "25000 revenue is Headline" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "ad-java-final-3",
        concept: "Loops",
        narrative: "Tobias is rehearsing his lines, repeating the affirmation five times.",
        prompt: "Use a `for` loop to print `\"I am a professional actor\"` exactly 5 times.",
        hint: "`for (int i = 0; i < 5; i++)` with `System.out.println`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 0; i < 5; i++) {\n      System.out.println("I am a professional actor");\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 0; i < ___; i++) {\n      System.out.println("I am a professional actor");\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "I am a professional actor\nI am a professional actor\nI am a professional actor\nI am a professional actor\nI am a professional actor", description: "Five affirmations" }],
        conceptKeywords: ["for", "i++", "System.out.println"],
      },
      {
        id: "ad-java-final-4",
        concept: "ArrayList",
        narrative: "Lucille keeps track of which ventures are still active — the list changes regularly.",
        prompt: "Create `ArrayList<String> ventures`. Add `\"Banana Stand\"`, `\"Bluth Original Homes\"`, `\"Cornballer\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> ventures = new ArrayList<>();\n    ventures.add("Banana Stand");\n    ventures.add("Bluth Original Homes");\n    ventures.add("Cornballer");\n    System.out.println(ventures);\n    System.out.println(ventures.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> ventures = new ArrayList<>();\n    ventures.add(___);\n    ventures.add(___);\n    ventures.add(___);\n    System.out.println(ventures);\n    System.out.println(ventures.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Banana Stand, Bluth Original Homes, Cornballer]\n3", description: "Active ventures" }],
        conceptKeywords: ["ArrayList", "add", "size"],
      },
      {
        id: "ad-java-final-5",
        concept: "HashMap",
        narrative: "Michael maps each family member to their current role so he knows who's responsible for what disaster.",
        prompt: "Create `HashMap<String, String> roles`. Put `\"Michael\" -> \"CEO\"`, `\"Gob\" -> \"Magician\"`, `\"Tobias\" -> \"Analrapist\"`. Print Gob's role and map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> roles = new HashMap<>();\n    roles.put("Michael", "CEO");\n    roles.put("Gob", "Magician");\n    roles.put("Tobias", "Analrapist");\n    System.out.println(roles.get("Gob"));\n    System.out.println(roles.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> roles = new HashMap<>();\n    roles.put("Michael", "CEO");\n    roles.put("Gob", "Magician");\n    roles.put("Tobias", "Analrapist");\n    System.out.println(roles.get(___));\n    System.out.println(roles.size());\n  }\n}`,
        testCases: [{ input: "", expected: "Magician\n3", description: "Gob's role and map size" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── Barbie ───────────────────────────────────────────────────────────────────
  "barbie-java": {
    id: "ba-java-final",
    themeId: "barbie",
    languageId: "java",
    themedTitle: "The Barbieland Java Test",
    introNarrative:
      "Weird Barbie says every Barbie needs to know Java to survive in the Real World. Five tests — pass them and you're officially a Barbie who can code. Ken is not required for this exam.",
    questions: [
      {
        id: "ba-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Barbie's career registration system needs her profile initialised.",
        prompt: "Declare `String name = \"Barbie\"`, `String career = \"Astronaut\"`, `boolean kenough = true`. Print all three.",
        hint: "All three are different data types.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String name = "Barbie";\n    String career = "Astronaut";\n    boolean kenough = true;\n    System.out.println(name);\n    System.out.println(career);\n    System.out.println(kenough);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String name = ___;\n    String career = ___;\n    boolean kenough = ___;\n    System.out.println(name);\n    System.out.println(career);\n    System.out.println(kenough);\n  }\n}`,
        testCases: [{ input: "", expected: "Barbie\nAstronaut\ntrue", description: "Barbie's profile" }],
        conceptKeywords: ["String", "boolean", "System.out.println"],
      },
      {
        id: "ba-java-final-2",
        concept: "Conditionals",
        narrative: "Ken's happiness rating determines whether he's allowed in the Mojo Dojo Casa House.",
        prompt: "Write `static String kenStatus(int happiness)` returning `\"Kenough\"` if happiness >= 8, `\"Learning\"` if >= 5, else `\"Needs Beach\"`. Call with 9, 6, 3.",
        hint: "Chain if/else if/else.",
        solution: `public class Main {\n  static String kenStatus(int happiness) {\n    if (happiness >= 8) return "Kenough";\n    else if (happiness >= 5) return "Learning";\n    else return "Needs Beach";\n  }\n  public static void main(String[] args) {\n    System.out.println(kenStatus(9));\n    System.out.println(kenStatus(6));\n    System.out.println(kenStatus(3));\n  }\n}`,
        starterCode: `public class Main {\n  static String kenStatus(int happiness) {\n    if (happiness >= 8) return ___;\n    else if (happiness >= 5) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(kenStatus(9));\n    System.out.println(kenStatus(6));\n    System.out.println(kenStatus(3));\n  }\n}`,
        testCases: [{ input: "9", expected: "Kenough", description: "Happiness 9 is Kenough" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "ba-java-final-3",
        concept: "Loops",
        narrative: "Each career Barbie must be introduced at the Barbieland grand ceremony.",
        prompt: "Create `String[] careers = {\"Doctor\", \"Astronaut\", \"President\", \"Mermaid\"}`. Loop and print each as `\"[career] Barbie!\"`.",
        hint: "For-each loop: `for (String career : careers)` then `System.out.println(career + \" Barbie!\")`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String[] careers = {"Doctor", "Astronaut", "President", "Mermaid"};\n    for (String career : careers) {\n      System.out.println(career + " Barbie!");\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String[] careers = {"Doctor", "Astronaut", "President", "Mermaid"};\n    for (String ___ : careers) {\n      System.out.println(___ + " Barbie!");\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "Doctor Barbie!\nAstronaut Barbie!\nPresident Barbie!\nMermaid Barbie!", description: "Barbie introductions" }],
        conceptKeywords: ["for", "String", "System.out.println"],
      },
      {
        id: "ba-java-final-4",
        concept: "ArrayList",
        narrative: "Barbie's Dream Closet inventory is always growing — an ArrayList handles new additions.",
        prompt: "Create `ArrayList<String> closet`. Add `\"Pink Gown\"`, `\"Space Suit\"`, `\"Doctor Coat\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> closet = new ArrayList<>();\n    closet.add("Pink Gown");\n    closet.add("Space Suit");\n    closet.add("Doctor Coat");\n    System.out.println(closet);\n    System.out.println(closet.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> closet = new ArrayList<>();\n    closet.add(___);\n    closet.add(___);\n    closet.add(___);\n    System.out.println(closet);\n    System.out.println(closet.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Pink Gown, Space Suit, Doctor Coat]\n3", description: "Dream Closet contents" }],
        conceptKeywords: ["ArrayList", "add", "size"],
      },
      {
        id: "ba-java-final-5",
        concept: "HashMap",
        narrative: "Ruth maps each Barbie's name to her primary career for the Mattel HR system.",
        prompt: "Create `HashMap<String, String> careers`. Put `\"Barbie\" -> \"Astronaut\"`, `\"President Barbie\" -> \"Politics\"`, `\"Weird Barbie\" -> \"Wisdom\"`. Print Weird Barbie's career and map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> careers = new HashMap<>();\n    careers.put("Barbie", "Astronaut");\n    careers.put("President Barbie", "Politics");\n    careers.put("Weird Barbie", "Wisdom");\n    System.out.println(careers.get("Weird Barbie"));\n    System.out.println(careers.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> careers = new HashMap<>();\n    careers.put("Barbie", "Astronaut");\n    careers.put("President Barbie", "Politics");\n    careers.put("Weird Barbie", "Wisdom");\n    System.out.println(careers.get(___));\n    System.out.println(careers.size());\n  }\n}`,
        testCases: [{ input: "", expected: "Wisdom\n3", description: "Weird Barbie's career" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── Sex and the City ─────────────────────────────────────────────────────────
  "sex-and-the-city-java": {
    id: "sc-java-final",
    themeId: "sex-and-the-city",
    languageId: "java",
    themedTitle: "The Manhattan Java Column",
    introNarrative:
      "I couldn't help but wonder — can Java bring us together? Five challenges await. Pour yourself a cosmo. It's time to find out if your code is a Manolo or a New Balance.",
    questions: [
      {
        id: "sc-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Carrie's column submission needs metadata entered into the Vogue Java publishing system.",
        prompt: "Declare `String author = \"Carrie Bradshaw\"`, `int wordCount = 1200`, `boolean published = false`. Print all three.",
        hint: "Standard Java variable declarations.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String author = "Carrie Bradshaw";\n    int wordCount = 1200;\n    boolean published = false;\n    System.out.println(author);\n    System.out.println(wordCount);\n    System.out.println(published);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String author = ___;\n    int wordCount = ___;\n    boolean published = ___;\n    System.out.println(author);\n    System.out.println(wordCount);\n    System.out.println(published);\n  }\n}`,
        testCases: [{ input: "", expected: "Carrie Bradshaw\n1200\nfalse", description: "Column metadata" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "sc-java-final-2",
        concept: "Conditionals",
        narrative: "Miranda's law firm ranks each case by its expected settlement value.",
        prompt: "Write `static String caseRank(int value)` returning `\"Partner-level\"` if value >= 500000, `\"Associate\"` if >= 100000, else `\"Pro bono\"`. Call with 600000, 150000, 50000.",
        hint: "Chain if/else if/else.",
        solution: `public class Main {\n  static String caseRank(int value) {\n    if (value >= 500000) return "Partner-level";\n    else if (value >= 100000) return "Associate";\n    else return "Pro bono";\n  }\n  public static void main(String[] args) {\n    System.out.println(caseRank(600000));\n    System.out.println(caseRank(150000));\n    System.out.println(caseRank(50000));\n  }\n}`,
        starterCode: `public class Main {\n  static String caseRank(int value) {\n    if (value >= 500000) return ___;\n    else if (value >= 100000) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(caseRank(600000));\n    System.out.println(caseRank(150000));\n    System.out.println(caseRank(50000));\n  }\n}`,
        testCases: [{ input: "600000", expected: "Partner-level", description: "600K is Partner-level" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "sc-java-final-3",
        concept: "Loops",
        narrative: "Charlotte is listing her art gallery's featured pieces for the opening night programme.",
        prompt: "Create `String[] pieces = {\"Blue Abstract\", \"Manhattan Sunrise\", \"Park Avenue\", \"The Kiss\"}`. Loop and print each piece.",
        hint: "For-each loop: `for (String piece : pieces)`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String[] pieces = {"Blue Abstract", "Manhattan Sunrise", "Park Avenue", "The Kiss"};\n    for (String piece : pieces) {\n      System.out.println(piece);\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String[] pieces = {"Blue Abstract", "Manhattan Sunrise", "Park Avenue", "The Kiss"};\n    for (String ___ : pieces) {\n      System.out.println(___);\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "Blue Abstract\nManhattan Sunrise\nPark Avenue\nThe Kiss", description: "Gallery pieces listed" }],
        conceptKeywords: ["for", "String", "System.out.println"],
      },
      {
        id: "sc-java-final-4",
        concept: "ArrayList",
        narrative: "Samantha's client list is always evolving — an ArrayList fits her dynamic social world.",
        prompt: "Create `ArrayList<String> clients`. Add `\"Smith PR\"`, `\"Jones Media\"`, `\"Manhattan Events\"`. Print the list and its size.",
        hint: "`import java.util.ArrayList;`",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> clients = new ArrayList<>();\n    clients.add("Smith PR");\n    clients.add("Jones Media");\n    clients.add("Manhattan Events");\n    System.out.println(clients);\n    System.out.println(clients.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> clients = new ArrayList<>();\n    clients.add(___);\n    clients.add(___);\n    clients.add(___);\n    System.out.println(clients);\n    System.out.println(clients.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Smith PR, Jones Media, Manhattan Events]\n3", description: "Samantha's client list" }],
        conceptKeywords: ["ArrayList", "add", "size"],
      },
      {
        id: "sc-java-final-5",
        concept: "HashMap",
        narrative: "Carrie maps each significant man to the year they dated for her final column draft.",
        prompt: "Create `HashMap<String, Integer> exes`. Put `\"Big\" -> 1998`, `\"Aidan\" -> 2001`, `\"Berger\" -> 2004`. Print Aidan's year and map size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> exes = new HashMap<>();\n    exes.put("Big", 1998);\n    exes.put("Aidan", 2001);\n    exes.put("Berger", 2004);\n    System.out.println(exes.get("Aidan"));\n    System.out.println(exes.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, Integer> exes = new HashMap<>();\n    exes.put("Big", 1998);\n    exes.put("Aidan", 2001);\n    exes.put("Berger", 2004);\n    System.out.println(exes.get(___));\n    System.out.println(exes.size());\n  }\n}`,
        testCases: [{ input: "", expected: "2001\n3", description: "Aidan's year and map size" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },

  // ── The Sopranos ─────────────────────────────────────────────────────────────
  "sopranos-java": {
    id: "sp-java-final",
    themeId: "sopranos",
    languageId: "java",
    themedTitle: "The Family Business Java Exam",
    introNarrative:
      "You come into my house on the day my daughter is to be married and you ask me to take a Java exam. Fine. Five problems. You do this right, you're with us. You don't, you talk to Silvio.",
    questions: [
      {
        id: "sp-java-final-1",
        concept: "Variables & Data Types",
        narrative: "Tony's waste management company needs its annual stats entered into the Java records system.",
        prompt: "Declare `String company = \"Barone Sanitation\"`, `int clients = 87`, `boolean profitable = true`. Print all three.",
        hint: "Standard Java declarations.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    String company = "Barone Sanitation";\n    int clients = 87;\n    boolean profitable = true;\n    System.out.println(company);\n    System.out.println(clients);\n    System.out.println(profitable);\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    String company = ___;\n    int clients = ___;\n    boolean profitable = ___;\n    System.out.println(company);\n    System.out.println(clients);\n    System.out.println(profitable);\n  }\n}`,
        testCases: [{ input: "", expected: "Barone Sanitation\n87\ntrue", description: "Company stats" }],
        conceptKeywords: ["String", "int", "boolean", "System.out.println"],
      },
      {
        id: "sp-java-final-2",
        concept: "Conditionals",
        narrative: "Tony's earner classification system ranks crew members based on their weekly contribution.",
        prompt: "Write `static String earnerRank(int weekly)` returning `\"Top earner\"` if weekly >= 50000, `\"Solid\"` if >= 20000, else `\"Needs improvement\"`. Call with 60000, 30000, 10000.",
        hint: "Chain if/else if/else.",
        solution: `public class Main {\n  static String earnerRank(int weekly) {\n    if (weekly >= 50000) return "Top earner";\n    else if (weekly >= 20000) return "Solid";\n    else return "Needs improvement";\n  }\n  public static void main(String[] args) {\n    System.out.println(earnerRank(60000));\n    System.out.println(earnerRank(30000));\n    System.out.println(earnerRank(10000));\n  }\n}`,
        starterCode: `public class Main {\n  static String earnerRank(int weekly) {\n    if (weekly >= 50000) return ___;\n    else if (weekly >= 20000) return ___;\n    else return ___;\n  }\n  public static void main(String[] args) {\n    System.out.println(earnerRank(60000));\n    System.out.println(earnerRank(30000));\n    System.out.println(earnerRank(10000));\n  }\n}`,
        testCases: [{ input: "60000", expected: "Top earner", description: "60K is Top earner" }],
        conceptKeywords: ["static", "if", "else", "return"],
      },
      {
        id: "sp-java-final-3",
        concept: "Loops",
        narrative: "Christopher is counting down Tony's weekly sessions with Dr. Melfi.",
        prompt: "Use a `for` loop to print `\"Session #N with Dr. Melfi\"` for N from 1 to 5.",
        hint: "`for (int i = 1; i <= 5; i++)` then `System.out.println`.",
        solution: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= 5; i++) {\n      System.out.println("Session #" + i + " with Dr. Melfi");\n    }\n  }\n}`,
        starterCode: `public class Main {\n  public static void main(String[] args) {\n    for (int i = 1; i <= ___; i++) {\n      System.out.println("Session #" + ___ + " with Dr. Melfi");\n    }\n  }\n}`,
        testCases: [{ input: "", expected: "Session #1 with Dr. Melfi\nSession #2 with Dr. Melfi\nSession #3 with Dr. Melfi\nSession #4 with Dr. Melfi\nSession #5 with Dr. Melfi", description: "Five therapy sessions" }],
        conceptKeywords: ["for", "i++", "System.out.println"],
      },
      {
        id: "sp-java-final-4",
        concept: "ArrayList",
        narrative: "Silvio maintains the Bada Bing's roster — it changes after every FBI sweep.",
        prompt: "Create `ArrayList<String> crew`. Add `\"Tony\"`, `\"Paulie\"`, `\"Christopher\"`, `\"Bobby\"`. Remove `\"Bobby\"` (he's unavailable). Print list and size.",
        hint: "Use `.remove(\"Bobby\")` to remove by value.",
        solution: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> crew = new ArrayList<>();\n    crew.add("Tony");\n    crew.add("Paulie");\n    crew.add("Christopher");\n    crew.add("Bobby");\n    crew.remove("Bobby");\n    System.out.println(crew);\n    System.out.println(crew.size());\n  }\n}`,
        starterCode: `import java.util.ArrayList;\npublic class Main {\n  public static void main(String[] args) {\n    ArrayList<String> crew = new ArrayList<>();\n    crew.add("Tony");\n    crew.add("Paulie");\n    crew.add("Christopher");\n    crew.add("Bobby");\n    crew.remove(___);\n    System.out.println(crew);\n    System.out.println(crew.size());\n  }\n}`,
        testCases: [{ input: "", expected: "[Tony, Paulie, Christopher]\n3", description: "Crew without Bobby" }],
        conceptKeywords: ["ArrayList", "add", "remove", "size"],
      },
      {
        id: "sp-java-final-5",
        concept: "HashMap",
        narrative: "Tony maps each crew member to their territory for the weekly tribute collection schedule.",
        prompt: "Create `HashMap<String, String> territories`. Put `\"Paulie\" -> \"North Jersey\"`, `\"Silvio\" -> \"Newark\"`, `\"Christopher\" -> \"Bloomfield\"`. Print Paulie's territory and size.",
        hint: "`import java.util.HashMap;`",
        solution: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> territories = new HashMap<>();\n    territories.put("Paulie", "North Jersey");\n    territories.put("Silvio", "Newark");\n    territories.put("Christopher", "Bloomfield");\n    System.out.println(territories.get("Paulie"));\n    System.out.println(territories.size());\n  }\n}`,
        starterCode: `import java.util.HashMap;\npublic class Main {\n  public static void main(String[] args) {\n    HashMap<String, String> territories = new HashMap<>();\n    territories.put("Paulie", "North Jersey");\n    territories.put("Silvio", "Newark");\n    territories.put("Christopher", "Bloomfield");\n    System.out.println(territories.get(___));\n    System.out.println(territories.size());\n  }\n}`,
        testCases: [{ input: "", expected: "North Jersey\n3", description: "Paulie's territory" }],
        conceptKeywords: ["HashMap", "put", "get"],
      },
    ],
  },
};
