import type { FinalChallenge } from "@/types";

export const javascriptFinalChallenges: Record<string, FinalChallenge> = {

  // ── Stranger Things ──────────────────────────────────────────────────────────
  "stranger-things-javascript": {
    id: "st-js-final",
    themeId: "stranger-things",
    languageId: "javascript",
    themedTitle: "The Hawkins Gauntlet",
    introNarrative:
      "The Mind Flayer has taken over Hawkins. Only coders who prove mastery of JavaScript can help the party fight back. Five challenges stand between you and saving the town.",
    questions: [
      {
        id: "st-js-final-1",
        concept: "Template Literals",
        narrative: "Mike needs to broadcast an urgent radio message to the party. The message must combine names and status dynamically.",
        prompt: "Write a function `radioMessage(name, status)` that returns a template literal string: `\"Hawkins Party: [name] is [status]\"`. Call it with `\"Eleven\"` and `\"found\"` and log the result.",
        hint: "Use backticks and `${variable}` syntax inside the template literal.",
        solution: `function radioMessage(name, status) {\n  return \`Hawkins Party: \${name} is \${status}\`;\n}\nconsole.log(radioMessage("Eleven", "found"));`,
        starterCode: `function radioMessage(name, status) {\n  return \`Hawkins Party: \${___} is \${___}\`;\n}\nconsole.log(radioMessage("Eleven", "found"));`,
        testCases: [{ input: "Eleven,found", expected: "Hawkins Party: Eleven is found", description: "Template literal message" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "st-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Dustin catalogued Upside Down creatures. The party only needs the dangerous ones — those with a threat score above 7.",
        prompt: "Given `const creatures = [{name:'Demogorgon',threat:9},{name:'Dart',threat:3},{name:'Mind Flayer',threat:10},{name:'Demodog',threat:6}]`, use `.filter()` to get only creatures with `threat > 7`. Log the names using `.map()`.",
        hint: "Chain `.filter(c => c.threat > 7).map(c => c.name)` then `console.log`.",
        solution: `const creatures = [{name:'Demogorgon',threat:9},{name:'Dart',threat:3},{name:'Mind Flayer',threat:10},{name:'Demodog',threat:6}];\nconst dangerous = creatures.filter(c => c.threat > 7).map(c => c.name);\nconsole.log(dangerous);`,
        starterCode: `const creatures = [{name:'Demogorgon',threat:9},{name:'Dart',threat:3},{name:'Mind Flayer',threat:10},{name:'Demodog',threat:6}];\nconst dangerous = creatures.filter(c => c.___ > 7).map(c => c.name);\nconsole.log(dangerous);`,
        testCases: [{ input: "", expected: "[ 'Demogorgon', 'Mind Flayer' ]", description: "Only high-threat creatures" }],
        conceptKeywords: ["filter", "map", "=>", "threat"],
      },
      {
        id: "st-js-final-3",
        concept: "Objects",
        narrative: "Hopper is filling in Eleven's official government file. The object must capture all key identity fields.",
        prompt: "Create an object `eleven` with properties: `name` (`\"Eleven\"`), `number` (`11`), `power` (`\"telekinesis\"`), and `missing` (`false`). Log `eleven.power` and `eleven.number`.",
        hint: "Use `const eleven = { key: value, ... };` and access with dot notation.",
        solution: `const eleven = { name: "Eleven", number: 11, power: "telekinesis", missing: false };\nconsole.log(eleven.power);\nconsole.log(eleven.number);`,
        starterCode: `const eleven = { name: "Eleven", number: ___, power: ___, missing: false };\nconsole.log(eleven.power);\nconsole.log(eleven.number);`,
        testCases: [{ input: "", expected: "telekinesis\n11", description: "Logs power and number" }],
        conceptKeywords: ["const", "{", ":", "console.log"],
      },
      {
        id: "st-js-final-4",
        concept: ".map()",
        narrative: "Joyce needs to convert every raw sighting record into an alert string for the bulletin board.",
        prompt: "Given `const sightings = ['Demogorgon spotted', 'strange lights', 'gate opened']`, use `.map()` to create a new array where every string is uppercased. Log the result.",
        hint: "Use `.map(s => s.toUpperCase())`.",
        solution: `const sightings = ['Demogorgon spotted', 'strange lights', 'gate opened'];\nconst alerts = sightings.map(s => s.toUpperCase());\nconsole.log(alerts);`,
        starterCode: `const sightings = ['Demogorgon spotted', 'strange lights', 'gate opened'];\nconst alerts = sightings.map(s => s.___());\nconsole.log(alerts);`,
        testCases: [{ input: "", expected: "[ 'DEMOGORGON SPOTTED', 'STRANGE LIGHTS', 'GATE OPENED' ]", description: "All uppercased" }],
        conceptKeywords: ["map", "toUpperCase", "=>"],
      },
      {
        id: "st-js-final-5",
        concept: ".reduce()",
        narrative: "The Party tracked how many encounters each member had with Upside Down creatures. Total them up so Hopper knows the full threat level.",
        prompt: "Given `const encounters = [3, 7, 2, 5, 9]`, use `.reduce()` to sum all values. Log the total.",
        hint: "Use `encounters.reduce((acc, val) => acc + val, 0)`.",
        solution: `const encounters = [3, 7, 2, 5, 9];\nconst total = encounters.reduce((acc, val) => acc + val, 0);\nconsole.log(total);`,
        starterCode: `const encounters = [3, 7, 2, 5, 9];\nconst total = encounters.reduce((acc, val) => acc + ___, 0);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "26", description: "Sum of all encounter counts" }],
        conceptKeywords: ["reduce", "acc", "=>", "0"],
      },
    ],
  },

  // ── Severance ────────────────────────────────────────────────────────────────
  "severance-javascript": {
    id: "sv-js-final",
    themeId: "severance",
    languageId: "javascript",
    themedTitle: "The Lumon JS Evaluation",
    introNarrative:
      "Lumon Industries has upgraded to JavaScript. Your severance chip requires re-verification. Mr. Milchick will administer five mandatory assessments. Complete them all to retain your employee status.",
    questions: [
      {
        id: "sv-js-final-1",
        concept: "Template Literals",
        narrative: "Milchick needs to generate personalised wellness session notifications for each MDR employee.",
        prompt: "Write `welcomeNote(name, score)` that returns `\"Welcome, [name]. Your wellness score is [score].\"` using a template literal. Log with `welcomeNote(\"Helly\", 72)`.",
        hint: "Use backticks: `\\`Welcome, ${name}. Your wellness score is ${score}.\\``",
        solution: `function welcomeNote(name, score) {\n  return \`Welcome, \${name}. Your wellness score is \${score}.\`;\n}\nconsole.log(welcomeNote("Helly", 72));`,
        starterCode: `function welcomeNote(name, score) {\n  return \`Welcome, \${___}. Your wellness score is \${___}.\`;\n}\nconsole.log(welcomeNote("Helly", 72));`,
        testCases: [{ input: "Helly,72", expected: "Welcome, Helly. Your wellness score is 72.", description: "Personalised welcome note" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "sv-js-final-2",
        concept: "Arrays & .push()",
        narrative: "The MDR team is growing. Irving needs to maintain the official department roster and track its size.",
        prompt: "Create `const mdr = ['Mark', 'Helly', 'Irving']`. Push `'Dylan'` to it. Log the array and then log its length.",
        hint: "Use `.push()` to add, then `console.log(mdr)` and `console.log(mdr.length)`.",
        solution: `const mdr = ['Mark', 'Helly', 'Irving'];\nmdr.push('Dylan');\nconsole.log(mdr);\nconsole.log(mdr.length);`,
        starterCode: `const mdr = ['Mark', 'Helly', 'Irving'];\nmdr.___('Dylan');\nconsole.log(mdr);\nconsole.log(mdr.length);`,
        testCases: [{ input: "", expected: "[ 'Mark', 'Helly', 'Irving', 'Dylan' ]\n4", description: "Array with Dylan added, length 4" }],
        conceptKeywords: ["push", "length", "console.log"],
      },
      {
        id: "sv-js-final-3",
        concept: "Functions & Ternary",
        narrative: "Cobel needs an instant classifier: are the employee's numbers in the acceptable range?",
        prompt: "Write `isCompliant(score)` that returns `'Compliant'` if `score >= 80`, else `'Non-compliant'`, using a ternary operator. Log with scores `90` and `45`.",
        hint: "Ternary: `condition ? 'value if true' : 'value if false'`.",
        solution: `function isCompliant(score) {\n  return score >= 80 ? 'Compliant' : 'Non-compliant';\n}\nconsole.log(isCompliant(90));\nconsole.log(isCompliant(45));`,
        starterCode: `function isCompliant(score) {\n  return score >= 80 ? ___ : ___;\n}\nconsole.log(isCompliant(90));\nconsole.log(isCompliant(45));`,
        testCases: [{ input: "90", expected: "Compliant", description: "90 is compliant" }],
        conceptKeywords: ["function", "return", "?", ":"],
      },
      {
        id: "sv-js-final-4",
        concept: ".map()",
        narrative: "The MDR team needs their bin completion rates converted from decimals to percentages.",
        prompt: "Given `const rates = [0.82, 0.47, 0.91, 0.63]`, use `.map()` to multiply each by 100 and round to the nearest integer with `Math.round()`. Log the result.",
        hint: "`.map(r => Math.round(r * 100))`",
        solution: `const rates = [0.82, 0.47, 0.91, 0.63];\nconst percentages = rates.map(r => Math.round(r * 100));\nconsole.log(percentages);`,
        starterCode: `const rates = [0.82, 0.47, 0.91, 0.63];\nconst percentages = rates.map(r => Math.round(r * ___));\nconsole.log(percentages);`,
        testCases: [{ input: "", expected: "[ 82, 47, 91, 63 ]", description: "Decimal rates as whole percentages" }],
        conceptKeywords: ["map", "Math.round", "=>", "100"],
      },
      {
        id: "sv-js-final-5",
        concept: "Object.keys() & Iteration",
        narrative: "The Board wants a full audit of MDR productivity scores. Log each employee name and their score.",
        prompt: "Given `const scores = { Mark: 88, Helly: 74, Irving: 95, Dylan: 61 }`, use `Object.keys()` to iterate and log each entry as `\"Mark: 88\"`.",
        hint: "Use `Object.keys(scores).forEach(key => console.log(...))`.",
        solution: `const scores = { Mark: 88, Helly: 74, Irving: 95, Dylan: 61 };\nObject.keys(scores).forEach(key => console.log(\`\${key}: \${scores[key]}\`));`,
        starterCode: `const scores = { Mark: 88, Helly: 74, Irving: 95, Dylan: 61 };\nObject.keys(scores).forEach(key => console.log(\`\${___}: \${scores[___]}\`));`,
        testCases: [{ input: "", expected: "Mark: 88\nHelly: 74\nIrving: 95\nDylan: 61", description: "All employee scores logged" }],
        conceptKeywords: ["Object.keys", "forEach", "=>", "`"],
      },
    ],
  },

  // ── Breaking Bad ─────────────────────────────────────────────────────────────
  "breaking-bad-javascript": {
    id: "bb-js-final",
    themeId: "breaking-bad",
    languageId: "javascript",
    themedTitle: "The Blue Sky Exam",
    introNarrative:
      "You want to cook? Then you prove it. Heisenberg doesn't tolerate mediocrity. Five problems stand between you and the perfect batch. Show your skills or walk away from the lab.",
    questions: [
      {
        id: "bb-js-final-1",
        concept: "Template Literals",
        narrative: "Jesse needs to format batch reports for the distribution network. Every report must be consistent and machine-readable.",
        prompt: "Write `batchReport(product, purity)` returning `\"Product: [product] | Purity: [purity]%\"` via template literal. Log with `batchReport('Blue Sky', 99.1)`.",
        hint: "Use backtick template with `${product}` and `${purity}`.",
        solution: `function batchReport(product, purity) {\n  return \`Product: \${product} | Purity: \${purity}%\`;\n}\nconsole.log(batchReport('Blue Sky', 99.1));`,
        starterCode: `function batchReport(product, purity) {\n  return \`Product: \${___} | Purity: \${___}%\`;\n}\nconsole.log(batchReport('Blue Sky', 99.1));`,
        testCases: [{ input: "Blue Sky,99.1", expected: "Product: Blue Sky | Purity: 99.1%", description: "Formatted batch report" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "bb-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Walter needs to sort his inventory — only batches with purity above 96% make the cut.",
        prompt: "Given `const batches = [{ id: 1, purity: 99.1 }, { id: 2, purity: 94.5 }, { id: 3, purity: 97.3 }, { id: 4, purity: 88.0 }]`, filter to only those with `purity > 96`. Log the result.",
        hint: "`.filter(b => b.purity > 96)`",
        solution: `const batches = [{id:1,purity:99.1},{id:2,purity:94.5},{id:3,purity:97.3},{id:4,purity:88.0}];\nconst premium = batches.filter(b => b.purity > 96);\nconsole.log(premium);`,
        starterCode: `const batches = [{id:1,purity:99.1},{id:2,purity:94.5},{id:3,purity:97.3},{id:4,purity:88.0}];\nconst premium = batches.filter(b => b.___ > 96);\nconsole.log(premium);`,
        testCases: [{ input: "", expected: "2", description: "Two batches above 96% purity" }],
        conceptKeywords: ["filter", "purity", "=>"],
      },
      {
        id: "bb-js-final-3",
        concept: "Objects",
        narrative: "Saul needs a full profile object for Heisenberg to use when dealing with the cartel.",
        prompt: "Create `const heisenberg = { alias: 'Heisenberg', product: 'Blue Sky', purity: 99.1, territory: 'Albuquerque' }`. Log `heisenberg.alias` and `heisenberg.purity`.",
        hint: "Object literal with `const`, then dot notation to access.",
        solution: `const heisenberg = { alias: 'Heisenberg', product: 'Blue Sky', purity: 99.1, territory: 'Albuquerque' };\nconsole.log(heisenberg.alias);\nconsole.log(heisenberg.purity);`,
        starterCode: `const heisenberg = { alias: ___, product: 'Blue Sky', purity: ___, territory: 'Albuquerque' };\nconsole.log(heisenberg.alias);\nconsole.log(heisenberg.purity);`,
        testCases: [{ input: "", expected: "Heisenberg\n99.1", description: "Alias and purity logged" }],
        conceptKeywords: ["const", "{", "alias", "console.log"],
      },
      {
        id: "bb-js-final-4",
        concept: ".map()",
        narrative: "Jesse's crew tracked their earnings per deal. Walter needs every value doubled for the reinvestment ledger.",
        prompt: "Given `const earnings = [5000, 12000, 8500, 21000]`, use `.map()` to double each value. Log the result.",
        hint: "`.map(n => n * 2)`",
        solution: `const earnings = [5000, 12000, 8500, 21000];\nconst doubled = earnings.map(n => n * 2);\nconsole.log(doubled);`,
        starterCode: `const earnings = [5000, 12000, 8500, 21000];\nconst doubled = earnings.map(n => n * ___);\nconsole.log(doubled);`,
        testCases: [{ input: "", expected: "[ 10000, 24000, 17000, 42000 ]", description: "Doubled earnings" }],
        conceptKeywords: ["map", "=>", "2"],
      },
      {
        id: "bb-js-final-5",
        concept: ".reduce()",
        narrative: "Skyler is auditing the car wash. Total up all the day's revenue for the books.",
        prompt: "Given `const revenue = [840, 1200, 655, 920, 1100]`, use `.reduce()` to sum the values. Log the total.",
        hint: "`revenue.reduce((acc, n) => acc + n, 0)`",
        solution: `const revenue = [840, 1200, 655, 920, 1100];\nconst total = revenue.reduce((acc, n) => acc + n, 0);\nconsole.log(total);`,
        starterCode: `const revenue = [840, 1200, 655, 920, 1100];\nconst total = revenue.reduce((acc, n) => acc + n, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "4715", description: "Total car wash revenue" }],
        conceptKeywords: ["reduce", "acc", "0", "=>"],
      },
    ],
  },

  // ── The Office ───────────────────────────────────────────────────────────────
  "the-office-javascript": {
    id: "to-js-final",
    themeId: "the-office",
    languageId: "javascript",
    themedTitle: "The Dunder Mifflin Performance Review",
    introNarrative:
      "Michael Scott has declared today 'JavaScript Appreciation Day.' The entire Scranton branch must pass five coding challenges or face a mandatory Fun Run. Dwight has agreed to grade submissions. Do not disappoint the Regional Manager.",
    questions: [
      {
        id: "to-js-final-1",
        concept: "Template Literals",
        narrative: "Michael needs to generate personalised performance review messages for every employee.",
        prompt: "Write `reviewMessage(name, rating)` returning `\"[name], your performance rating is [rating]/10. That's what she said.\"` via template literal. Log with `reviewMessage('Dwight', 9)`.",
        hint: "Use backtick template literal with `${}` placeholders.",
        solution: `function reviewMessage(name, rating) {\n  return \`\${name}, your performance rating is \${rating}/10. That's what she said.\`;\n}\nconsole.log(reviewMessage('Dwight', 9));`,
        starterCode: `function reviewMessage(name, rating) {\n  return \`\${___}, your performance rating is \${___}/10. That's what she said.\`;\n}\nconsole.log(reviewMessage('Dwight', 9));`,
        testCases: [{ input: "Dwight,9", expected: "Dwight, your performance rating is 9/10. That's what she said.", description: "Performance review message" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "to-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Jim is filtering the sales leaderboard. Only reps who hit quota deserve the Pizza by Alfredo upgrade.",
        prompt: "Given `const sales = [{name:'Dwight',total:15000},{name:'Jim',total:9500},{name:'Andy',total:12000},{name:'Phyllis',total:8000}]`, filter those with `total >= 10000`. Log the names.",
        hint: "`.filter(s => s.total >= 10000).map(s => s.name)`",
        solution: `const sales = [{name:'Dwight',total:15000},{name:'Jim',total:9500},{name:'Andy',total:12000},{name:'Phyllis',total:8000}];\nconst topSellers = sales.filter(s => s.total >= 10000).map(s => s.name);\nconsole.log(topSellers);`,
        starterCode: `const sales = [{name:'Dwight',total:15000},{name:'Jim',total:9500},{name:'Andy',total:12000},{name:'Phyllis',total:8000}];\nconst topSellers = sales.filter(s => s.total >= ___).map(s => s.name);\nconsole.log(topSellers);`,
        testCases: [{ input: "", expected: "[ 'Dwight', 'Andy' ]", description: "Reps who hit quota" }],
        conceptKeywords: ["filter", "map", "total", "=>"],
      },
      {
        id: "to-js-final-3",
        concept: "Objects",
        narrative: "Dwight needs a complete profile object for his volunteer sheriff deputy application.",
        prompt: "Create `const dwight = { name: 'Dwight Schrute', title: 'Assistant Regional Manager', beets: true, nunchucks: true }`. Log `dwight.title` and `dwight.beets`.",
        hint: "Object literal, then dot notation access.",
        solution: `const dwight = { name: 'Dwight Schrute', title: 'Assistant Regional Manager', beets: true, nunchucks: true };\nconsole.log(dwight.title);\nconsole.log(dwight.beets);`,
        starterCode: `const dwight = { name: 'Dwight Schrute', title: ___, beets: true, nunchucks: true };\nconsole.log(dwight.title);\nconsole.log(dwight.beets);`,
        testCases: [{ input: "", expected: "Assistant Regional Manager\ntrue", description: "Title and beets status" }],
        conceptKeywords: ["const", "{", "title", "console.log"],
      },
      {
        id: "to-js-final-4",
        concept: ".map()",
        narrative: "Michael wants every branch name in ALL CAPS for the company-wide announcement banner.",
        prompt: "Given `const branches = ['Scranton', 'Stamford', 'Nashua', 'Albany']`, use `.map()` to uppercase all. Log the result.",
        hint: "`.map(b => b.toUpperCase())`",
        solution: `const branches = ['Scranton', 'Stamford', 'Nashua', 'Albany'];\nconst shoutBranches = branches.map(b => b.toUpperCase());\nconsole.log(shoutBranches);`,
        starterCode: `const branches = ['Scranton', 'Stamford', 'Nashua', 'Albany'];\nconst shoutBranches = branches.map(b => b.___());\nconsole.log(shoutBranches);`,
        testCases: [{ input: "", expected: "[ 'SCRANTON', 'STAMFORD', 'NASHUA', 'ALBANY' ]", description: "All branch names uppercased" }],
        conceptKeywords: ["map", "toUpperCase", "=>"],
      },
      {
        id: "to-js-final-5",
        concept: ".reduce()",
        narrative: "Kevin is doing the quarterly totals. Add up all the paper sales across the region.",
        prompt: "Given `const monthlySales = [42000, 38000, 51000, 47000, 39000]`, use `.reduce()` to find the total. Log it.",
        hint: "`.reduce((acc, n) => acc + n, 0)`",
        solution: `const monthlySales = [42000, 38000, 51000, 47000, 39000];\nconst total = monthlySales.reduce((acc, n) => acc + n, 0);\nconsole.log(total);`,
        starterCode: `const monthlySales = [42000, 38000, 51000, 47000, 39000];\nconst total = monthlySales.reduce((acc, n) => acc + ___, 0);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "217000", description: "Total regional paper sales" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── Game of Thrones ──────────────────────────────────────────────────────────
  "game-of-thrones-javascript": {
    id: "got-js-final",
    themeId: "game-of-thrones",
    languageId: "javascript",
    themedTitle: "The Maester's Trial",
    introNarrative:
      "The Grand Maester has called for trials at the Citadel. To be awarded a chain link — and the right to advise the realm — you must prove your mastery across five disciplines of JavaScript.",
    questions: [
      {
        id: "got-js-final-1",
        concept: "Template Literals",
        narrative: "Ravens must carry precise messages between the great houses. Format this dispatch correctly.",
        prompt: "Write `ravenMessage(from, to, msg)` returning `\"From [from] to [to]: [msg]\"` via template literal. Log with `ravenMessage('Winterfell', 'The Wall', 'Winter is coming')`.",
        hint: "Template literal: `\\`From ${from} to ${to}: ${msg}\\``",
        solution: `function ravenMessage(from, to, msg) {\n  return \`From \${from} to \${to}: \${msg}\`;\n}\nconsole.log(ravenMessage('Winterfell', 'The Wall', 'Winter is coming'));`,
        starterCode: `function ravenMessage(from, to, msg) {\n  return \`From \${___} to \${___}: \${___}\`;\n}\nconsole.log(ravenMessage('Winterfell', 'The Wall', 'Winter is coming'));`,
        testCases: [{ input: "", expected: "From Winterfell to The Wall: Winter is coming", description: "Formatted raven message" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "got-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Jon Snow needs to identify which houses have pledged enough swords to defend the North.",
        prompt: "Given `const houses = [{name:'Stark',swords:5000},{name:'Lannister',swords:8000},{name:'Tully',swords:2000},{name:'Arryn',swords:3500}]`, filter those with `swords >= 4000` and log their names.",
        hint: "`.filter(h => h.swords >= 4000).map(h => h.name)`",
        solution: `const houses = [{name:'Stark',swords:5000},{name:'Lannister',swords:8000},{name:'Tully',swords:2000},{name:'Arryn',swords:3500}];\nconst allies = houses.filter(h => h.swords >= 4000).map(h => h.name);\nconsole.log(allies);`,
        starterCode: `const houses = [{name:'Stark',swords:5000},{name:'Lannister',swords:8000},{name:'Tully',swords:2000},{name:'Arryn',swords:3500}];\nconst allies = houses.filter(h => h.swords >= ___).map(h => h.name);\nconsole.log(allies);`,
        testCases: [{ input: "", expected: "[ 'Stark', 'Lannister' ]", description: "Houses with 4000+ swords" }],
        conceptKeywords: ["filter", "map", "swords", "=>"],
      },
      {
        id: "got-js-final-3",
        concept: "Objects",
        narrative: "The Small Council needs an official profile entry for each Lord Commander.",
        prompt: "Create `const jonSnow = { name: 'Jon Snow', title: 'Lord Commander', house: 'Stark', dragons: 0 }`. Log `jonSnow.title` and `jonSnow.house`.",
        hint: "Object literal, dot notation.",
        solution: `const jonSnow = { name: 'Jon Snow', title: 'Lord Commander', house: 'Stark', dragons: 0 };\nconsole.log(jonSnow.title);\nconsole.log(jonSnow.house);`,
        starterCode: `const jonSnow = { name: 'Jon Snow', title: ___, house: ___, dragons: 0 };\nconsole.log(jonSnow.title);\nconsole.log(jonSnow.house);`,
        testCases: [{ input: "", expected: "Lord Commander\nStark", description: "Title and house" }],
        conceptKeywords: ["const", "title", "house", "console.log"],
      },
      {
        id: "got-js-final-4",
        concept: ".map()",
        narrative: "Daenerys needs the names of all her dragons formatted as a proclamation list.",
        prompt: "Given `const dragons = ['Drogon', 'Rhaegal', 'Viserion']`, use `.map()` to prepend `'Dragon: '` to each name. Log the result.",
        hint: "`.map(d => 'Dragon: ' + d)` or use a template literal.",
        solution: `const dragons = ['Drogon', 'Rhaegal', 'Viserion'];\nconst proclamation = dragons.map(d => \`Dragon: \${d}\`);\nconsole.log(proclamation);`,
        starterCode: `const dragons = ['Drogon', 'Rhaegal', 'Viserion'];\nconst proclamation = dragons.map(d => \`Dragon: \${___}\`);\nconsole.log(proclamation);`,
        testCases: [{ input: "", expected: "[ 'Dragon: Drogon', 'Dragon: Rhaegal', 'Dragon: Viserion' ]", description: "Dragon proclamation list" }],
        conceptKeywords: ["map", "=>", "`", "${"],
      },
      {
        id: "got-js-final-5",
        concept: ".reduce()",
        narrative: "The Master of Coin needs to tally the total gold in the treasury across all seven kingdoms.",
        prompt: "Given `const gold = [12000, 8500, 21000, 4000, 16500, 9000, 7200]`, use `.reduce()` to find the total. Log it.",
        hint: "`gold.reduce((acc, g) => acc + g, 0)`",
        solution: `const gold = [12000, 8500, 21000, 4000, 16500, 9000, 7200];\nconst treasury = gold.reduce((acc, g) => acc + g, 0);\nconsole.log(treasury);`,
        starterCode: `const gold = [12000, 8500, 21000, 4000, 16500, 9000, 7200];\nconst treasury = gold.reduce((acc, g) => acc + g, ___);\nconsole.log(treasury);`,
        testCases: [{ input: "", expected: "78200", description: "Total gold in the treasury" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── The Matrix ───────────────────────────────────────────────────────────────
  "the-matrix-javascript": {
    id: "mx-js-final",
    themeId: "the-matrix",
    languageId: "javascript",
    themedTitle: "The Oracle's Final Test",
    introNarrative:
      "You've taken the red pill. The Oracle has set five tests to determine if you are truly The One. Pass them all and the Matrix bends to your will.",
    questions: [
      {
        id: "mx-js-final-1",
        concept: "Template Literals",
        narrative: "Morpheus needs a dynamic briefing system for new recruits entering the ship.",
        prompt: "Write `brief(name, role)` returning `\"[name], you are the [role]. The Matrix has you.\"` via template literal. Log with `brief('Neo', 'One')`.",
        hint: "Use backtick template with `${}` placeholders.",
        solution: `function brief(name, role) {\n  return \`\${name}, you are the \${role}. The Matrix has you.\`;\n}\nconsole.log(brief('Neo', 'One'));`,
        starterCode: `function brief(name, role) {\n  return \`\${___}, you are the \${___}. The Matrix has you.\`;\n}\nconsole.log(brief('Neo', 'One'));`,
        testCases: [{ input: "Neo,One", expected: "Neo, you are the One. The Matrix has you.", description: "Briefing message" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "mx-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "The Operator needs to filter agents from the resistance database — only entities above threat level 8 are Agent Smith clones.",
        prompt: "Given `const entities = [{name:'Agent Smith',threat:10},{name:'Oracle',threat:2},{name:'Agent Brown',threat:8},{name:'Seraph',threat:5}]`, filter those with `threat >= 8` and log their names.",
        hint: "`.filter(e => e.threat >= 8).map(e => e.name)`",
        solution: `const entities = [{name:'Agent Smith',threat:10},{name:'Oracle',threat:2},{name:'Agent Brown',threat:8},{name:'Seraph',threat:5}];\nconst agents = entities.filter(e => e.threat >= 8).map(e => e.name);\nconsole.log(agents);`,
        starterCode: `const entities = [{name:'Agent Smith',threat:10},{name:'Oracle',threat:2},{name:'Agent Brown',threat:8},{name:'Seraph',threat:5}];\nconst agents = entities.filter(e => e.threat >= ___).map(e => e.name);\nconsole.log(agents);`,
        testCases: [{ input: "", expected: "[ 'Agent Smith', 'Agent Brown' ]", description: "High-threat agents" }],
        conceptKeywords: ["filter", "map", "threat", "=>"],
      },
      {
        id: "mx-js-final-3",
        concept: "Objects",
        narrative: "Trinity compiles a dossier on every operative for mission planning.",
        prompt: "Create `const neo = { name: 'Neo', realName: 'Thomas Anderson', awakened: true, spoons: 0 }`. Log `neo.realName` and `neo.awakened`.",
        hint: "Object literal with dot notation access.",
        solution: `const neo = { name: 'Neo', realName: 'Thomas Anderson', awakened: true, spoons: 0 };\nconsole.log(neo.realName);\nconsole.log(neo.awakened);`,
        starterCode: `const neo = { name: 'Neo', realName: ___, awakened: ___, spoons: 0 };\nconsole.log(neo.realName);\nconsole.log(neo.awakened);`,
        testCases: [{ input: "", expected: "Thomas Anderson\ntrue", description: "Real name and awakened status" }],
        conceptKeywords: ["const", "realName", "awakened", "console.log"],
      },
      {
        id: "mx-js-final-4",
        concept: ".map()",
        narrative: "Tank is processing simulation coordinates — each value needs to be squared for the targeting algorithm.",
        prompt: "Given `const coords = [3, 7, 2, 5, 4]`, use `.map()` to return each value squared (`n * n`). Log the result.",
        hint: "`.map(n => n * n)`",
        solution: `const coords = [3, 7, 2, 5, 4];\nconst squared = coords.map(n => n * n);\nconsole.log(squared);`,
        starterCode: `const coords = [3, 7, 2, 5, 4];\nconst squared = coords.map(n => n * ___);\nconsole.log(squared);`,
        testCases: [{ input: "", expected: "[ 9, 49, 4, 25, 16 ]", description: "Squared coordinates" }],
        conceptKeywords: ["map", "=>", "n"],
      },
      {
        id: "mx-js-final-5",
        concept: ".reduce()",
        narrative: "The Architect calculates the total processing power across all Matrix nodes.",
        prompt: "Given `const nodes = [1200, 850, 2100, 1600, 900]`, use `.reduce()` to sum all processing power. Log the total.",
        hint: "`.reduce((acc, n) => acc + n, 0)`",
        solution: `const nodes = [1200, 850, 2100, 1600, 900];\nconst total = nodes.reduce((acc, n) => acc + n, 0);\nconsole.log(total);`,
        starterCode: `const nodes = [1200, 850, 2100, 1600, 900];\nconst total = nodes.reduce((acc, n) => acc + n, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "6650", description: "Total processing power" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── Rick and Morty ───────────────────────────────────────────────────────────
  "rick-and-morty-javascript": {
    id: "rm-js-final",
    themeId: "rick-and-morty",
    languageId: "javascript",
    themedTitle: "Rick's Citadel Certification Exam",
    introNarrative:
      "Wubba lubba dub dub! Rick has trapped you in a dimension where you must pass five JavaScript challenges to get the portal gun back. He swears it's only because the challenges are *burp* educational.",
    questions: [
      {
        id: "rm-js-final-1",
        concept: "Template Literals",
        narrative: "Rick needs to label every dimension in the portal directory. Generate the entry automatically.",
        prompt: "Write `dimensionLabel(id, type)` returning `\"Dimension [id]: [type] universe\"` via template literal. Log with `dimensionLabel('C-137', 'prime')`.",
        hint: "Backtick template: `\\`Dimension ${id}: ${type} universe\\``",
        solution: `function dimensionLabel(id, type) {\n  return \`Dimension \${id}: \${type} universe\`;\n}\nconsole.log(dimensionLabel('C-137', 'prime'));`,
        starterCode: `function dimensionLabel(id, type) {\n  return \`Dimension \${___}: \${___} universe\`;\n}\nconsole.log(dimensionLabel('C-137', 'prime'));`,
        testCases: [{ input: "C-137,prime", expected: "Dimension C-137: prime universe", description: "Dimension label" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "rm-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "The Council of Ricks needs to remove unstable portals from the active list — only those with stability above 70 are safe.",
        prompt: "Given `const portals = [{id:'P1',stability:85},{id:'P2',stability:42},{id:'P3',stability:91},{id:'P4',stability:60}]`, filter those with `stability > 70`. Log their IDs.",
        hint: "`.filter(p => p.stability > 70).map(p => p.id)`",
        solution: `const portals = [{id:'P1',stability:85},{id:'P2',stability:42},{id:'P3',stability:91},{id:'P4',stability:60}];\nconst safe = portals.filter(p => p.stability > 70).map(p => p.id);\nconsole.log(safe);`,
        starterCode: `const portals = [{id:'P1',stability:85},{id:'P2',stability:42},{id:'P3',stability:91},{id:'P4',stability:60}];\nconst safe = portals.filter(p => p.stability > ___).map(p => p.id);\nconsole.log(safe);`,
        testCases: [{ input: "", expected: "[ 'P1', 'P3' ]", description: "Stable portals only" }],
        conceptKeywords: ["filter", "map", "stability", "=>"],
      },
      {
        id: "rm-js-final-3",
        concept: "Objects",
        narrative: "Morty needs Rick to record his interdimensional profile before the next adventure.",
        prompt: "Create `const rick = { name: 'Rick Sanchez', dimension: 'C-137', iq: 312, catchphrase: 'Wubba lubba dub dub' }`. Log `rick.iq` and `rick.dimension`.",
        hint: "Object literal, then dot notation.",
        solution: `const rick = { name: 'Rick Sanchez', dimension: 'C-137', iq: 312, catchphrase: 'Wubba lubba dub dub' };\nconsole.log(rick.iq);\nconsole.log(rick.dimension);`,
        starterCode: `const rick = { name: 'Rick Sanchez', dimension: ___, iq: ___, catchphrase: 'Wubba lubba dub dub' };\nconsole.log(rick.iq);\nconsole.log(rick.dimension);`,
        testCases: [{ input: "", expected: "312\nC-137", description: "IQ and dimension" }],
        conceptKeywords: ["const", "iq", "dimension", "console.log"],
      },
      {
        id: "rm-js-final-4",
        concept: ".map()",
        narrative: "Every Meeseeks has a task number. Triple each number for the advanced task assignment protocol.",
        prompt: "Given `const tasks = [1, 2, 3, 4, 5]`, use `.map()` to triple each. Log the result.",
        hint: "`.map(n => n * 3)`",
        solution: `const tasks = [1, 2, 3, 4, 5];\nconst tripled = tasks.map(n => n * 3);\nconsole.log(tripled);`,
        starterCode: `const tasks = [1, 2, 3, 4, 5];\nconst tripled = tasks.map(n => n * ___);\nconsole.log(tripled);`,
        testCases: [{ input: "", expected: "[ 3, 6, 9, 12, 15 ]", description: "Tripled task numbers" }],
        conceptKeywords: ["map", "=>", "3"],
      },
      {
        id: "rm-js-final-5",
        concept: ".reduce()",
        narrative: "Rick tallies up all the Szechuan sauce packets he's collected across dimensions.",
        prompt: "Given `const packets = [14, 6, 22, 9, 31]`, use `.reduce()` to find the total. Log it.",
        hint: "`.reduce((acc, p) => acc + p, 0)`",
        solution: `const packets = [14, 6, 22, 9, 31];\nconst total = packets.reduce((acc, p) => acc + p, 0);\nconsole.log(total);`,
        starterCode: `const packets = [14, 6, 22, 9, 31];\nconst total = packets.reduce((acc, p) => acc + p, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "82", description: "Total Szechuan sauce packets" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── Squid Game ───────────────────────────────────────────────────────────────
  "squid-game-javascript": {
    id: "sg-js-final",
    themeId: "squid-game",
    languageId: "javascript",
    themedTitle: "The Front Man's Final Game",
    introNarrative:
      "456 players entered. Only one can claim the prize. The Front Man has designed five JavaScript challenges as the final stage. Fail any one and you're eliminated.",
    questions: [
      {
        id: "sg-js-final-1",
        concept: "Template Literals",
        narrative: "The announcer needs to call each player's number before the game begins.",
        prompt: "Write `callPlayer(number, game)` returning `\"Player [number], welcome to [game].\"` via template literal. Log with `callPlayer(456, 'Red Light Green Light')`.",
        hint: "Backtick template with `${}` for each variable.",
        solution: `function callPlayer(number, game) {\n  return \`Player \${number}, welcome to \${game}.\`;\n}\nconsole.log(callPlayer(456, 'Red Light Green Light'));`,
        starterCode: `function callPlayer(number, game) {\n  return \`Player \${___}, welcome to \${___}.\`;\n}\nconsole.log(callPlayer(456, 'Red Light Green Light'));`,
        testCases: [{ input: "456,Red Light Green Light", expected: "Player 456, welcome to Red Light Green Light.", description: "Player announcement" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "sg-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "After each game, only survivors continue. Filter the remaining players from the full list.",
        prompt: "Given `const players = [{number:1,alive:false},{number:67,alive:true},{number:218,alive:true},{number:101,alive:false},{number:456,alive:true}]`, filter the alive ones and log their numbers.",
        hint: "`.filter(p => p.alive).map(p => p.number)`",
        solution: `const players = [{number:1,alive:false},{number:67,alive:true},{number:218,alive:true},{number:101,alive:false},{number:456,alive:true}];\nconst survivors = players.filter(p => p.alive).map(p => p.number);\nconsole.log(survivors);`,
        starterCode: `const players = [{number:1,alive:false},{number:67,alive:true},{number:218,alive:true},{number:101,alive:false},{number:456,alive:true}];\nconst survivors = players.filter(p => p.___).map(p => p.number);\nconsole.log(survivors);`,
        testCases: [{ input: "", expected: "[ 67, 218, 456 ]", description: "Surviving player numbers" }],
        conceptKeywords: ["filter", "map", "alive", "=>"],
      },
      {
        id: "sg-js-final-3",
        concept: "Objects",
        narrative: "The VIP observers need a profile card for each finalist.",
        prompt: "Create `const player456 = { number: 456, name: 'Seong Gi-hun', game: 'Marbles', status: 'alive' }`. Log `player456.name` and `player456.status`.",
        hint: "Object literal, dot notation.",
        solution: `const player456 = { number: 456, name: 'Seong Gi-hun', game: 'Marbles', status: 'alive' };\nconsole.log(player456.name);\nconsole.log(player456.status);`,
        starterCode: `const player456 = { number: 456, name: ___, game: 'Marbles', status: ___ };\nconsole.log(player456.name);\nconsole.log(player456.status);`,
        testCases: [{ input: "", expected: "Seong Gi-hun\nalive", description: "Player name and status" }],
        conceptKeywords: ["const", "name", "status", "console.log"],
      },
      {
        id: "sg-js-final-4",
        concept: ".map()",
        narrative: "The prize amounts grow by game. Triple each base prize to calculate the final round values.",
        prompt: "Given `const prizes = [1000000, 2000000, 5000000, 10000000]`, use `.map()` to multiply each by 3. Log the result.",
        hint: "`.map(p => p * 3)`",
        solution: `const prizes = [1000000, 2000000, 5000000, 10000000];\nconst tripled = prizes.map(p => p * 3);\nconsole.log(tripled);`,
        starterCode: `const prizes = [1000000, 2000000, 5000000, 10000000];\nconst tripled = prizes.map(p => p * ___);\nconsole.log(tripled);`,
        testCases: [{ input: "", expected: "[ 3000000, 6000000, 15000000, 30000000 ]", description: "Tripled prize amounts" }],
        conceptKeywords: ["map", "=>", "3"],
      },
      {
        id: "sg-js-final-5",
        concept: ".reduce()",
        narrative: "The Front Man tallies the total debt carried by all participants entering the games.",
        prompt: "Given `const debts = [160000000, 250000000, 80000000, 420000000, 95000000]`, use `.reduce()` to find the total. Log it.",
        hint: "`.reduce((acc, d) => acc + d, 0)`",
        solution: `const debts = [160000000, 250000000, 80000000, 420000000, 95000000];\nconst total = debts.reduce((acc, d) => acc + d, 0);\nconsole.log(total);`,
        starterCode: `const debts = [160000000, 250000000, 80000000, 420000000, 95000000];\nconst total = debts.reduce((acc, d) => acc + d, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "1005000000", description: "Total participant debt" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── Arrested Development ─────────────────────────────────────────────────────
  "arrested-development-javascript": {
    id: "ad-js-final",
    themeId: "arrested-development",
    languageId: "javascript",
    themedTitle: "The Bluth Company Audit",
    introNarrative:
      "The SEC has frozen the Bluth Company's assets — again. Michael needs someone who can pass five JavaScript challenges to prove the company's books are legitimate. There's always money in the banana stand... if you can code your way to it.",
    questions: [
      {
        id: "ad-js-final-1",
        concept: "Template Literals",
        narrative: "Michael needs to generate official business memos that combine employee names and their assigned ventures.",
        prompt: "Write `memo(employee, venture)` returning `\"[employee] is now managing [venture].\"` via template literal. Log with `memo('Michael Bluth', 'The Banana Stand')`.",
        hint: "Use backtick with `${}` for each variable.",
        solution: `function memo(employee, venture) {\n  return \`\${employee} is now managing \${venture}.\`;\n}\nconsole.log(memo('Michael Bluth', 'The Banana Stand'));`,
        starterCode: `function memo(employee, venture) {\n  return \`\${___} is now managing \${___}.\`;\n}\nconsole.log(memo('Michael Bluth', 'The Banana Stand'));`,
        testCases: [{ input: "Michael Bluth,The Banana Stand", expected: "Michael Bluth is now managing The Banana Stand.", description: "Business memo" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "ad-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Lucille needs to filter out the profitable ventures from the Bluth Company portfolio — only those making over $50,000.",
        prompt: "Given `const ventures = [{name:'Banana Stand',profit:250000},{name:'Cornballer',profit:-15000},{name:'Bluth Homes',profit:80000},{name:'Gobias Industries',profit:5000}]`, filter `profit > 50000` and log the names.",
        hint: "`.filter(v => v.profit > 50000).map(v => v.name)`",
        solution: `const ventures = [{name:'Banana Stand',profit:250000},{name:'Cornballer',profit:-15000},{name:'Bluth Homes',profit:80000},{name:'Gobias Industries',profit:5000}];\nconst profitable = ventures.filter(v => v.profit > 50000).map(v => v.name);\nconsole.log(profitable);`,
        starterCode: `const ventures = [{name:'Banana Stand',profit:250000},{name:'Cornballer',profit:-15000},{name:'Bluth Homes',profit:80000},{name:'Gobias Industries',profit:5000}];\nconst profitable = ventures.filter(v => v.profit > ___).map(v => v.name);\nconsole.log(profitable);`,
        testCases: [{ input: "", expected: "[ 'Banana Stand', 'Bluth Homes' ]", description: "Profitable ventures" }],
        conceptKeywords: ["filter", "map", "profit", "=>"],
      },
      {
        id: "ad-js-final-3",
        concept: "Ternary Operator",
        narrative: "Gob needs an instant verdict on whether his illusions are profitable enough to continue — \"It's not a trick, it's an ILLUSION!\"",
        prompt: "Write `illusionVerdict(revenue)` using a ternary that returns `'Book it!'` if `revenue >= 10000`, else `'It's a trick...'`. Log with `illusionVerdict(15000)` and `illusionVerdict(3000)`.",
        hint: "Ternary: `revenue >= 10000 ? 'Book it!' : \"It's a trick...\"`",
        solution: `function illusionVerdict(revenue) {\n  return revenue >= 10000 ? 'Book it!' : "It's a trick...";\n}\nconsole.log(illusionVerdict(15000));\nconsole.log(illusionVerdict(3000));`,
        starterCode: `function illusionVerdict(revenue) {\n  return revenue >= 10000 ? ___ : ___;\n}\nconsole.log(illusionVerdict(15000));\nconsole.log(illusionVerdict(3000));`,
        testCases: [{ input: "15000", expected: "Book it!", description: "High revenue books the illusion" }],
        conceptKeywords: ["function", "return", "?", ":"],
      },
      {
        id: "ad-js-final-4",
        concept: ".map()",
        narrative: "Tobias needs all his acting credits formatted for his headshot envelope — each one needs the prefix 'ROLE: '.",
        prompt: "Given `const credits = ['Dr. Fünke', 'Mrs. Featherbottom', 'Carl Weathers understudy']`, use `.map()` to prepend `'ROLE: '` to each. Log the result.",
        hint: "`.map(c => 'ROLE: ' + c)` or use a template literal.",
        solution: `const credits = ['Dr. Fünke', 'Mrs. Featherbottom', 'Carl Weathers understudy'];\nconst formatted = credits.map(c => \`ROLE: \${c}\`);\nconsole.log(formatted);`,
        starterCode: `const credits = ['Dr. Fünke', 'Mrs. Featherbottom', 'Carl Weathers understudy'];\nconst formatted = credits.map(c => \`ROLE: \${___}\`);\nconsole.log(formatted);`,
        testCases: [{ input: "", expected: "[ 'ROLE: Dr. Fünke', 'ROLE: Mrs. Featherbottom', 'ROLE: Carl Weathers understudy' ]", description: "Formatted acting credits" }],
        conceptKeywords: ["map", "=>", "`", "${"],
      },
      {
        id: "ad-js-final-5",
        concept: ".reduce()",
        narrative: "George Sr. wants to know the total hidden value across all banana stand locations before the walls get burned down again.",
        prompt: "Given `const wallCash = [62500, 62500, 62500, 62500]` (one entry per wall), use `.reduce()` to total it up. Log the result.",
        hint: "`.reduce((acc, n) => acc + n, 0)` — there's always money in the banana stand.",
        solution: `const wallCash = [62500, 62500, 62500, 62500];\nconst total = wallCash.reduce((acc, n) => acc + n, 0);\nconsole.log(total);`,
        starterCode: `const wallCash = [62500, 62500, 62500, 62500];\nconst total = wallCash.reduce((acc, n) => acc + n, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "250000", description: "Total banana stand wall cash" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── Barbie ───────────────────────────────────────────────────────────────────
  "barbie-javascript": {
    id: "ba-js-final",
    themeId: "barbie",
    languageId: "javascript",
    themedTitle: "The Barbieland Competency Test",
    introNarrative:
      "You've arrived in Barbieland — and everything is awesome! But to stay, you must prove you can code. Weird Barbie has set five JavaScript challenges. Complete them and you're officially a Barbie. Fail and you go to the Real World.",
    questions: [
      {
        id: "ba-js-final-1",
        concept: "Template Literals",
        narrative: "Every Barbie needs a personalised greeting for her career debut in Barbieland.",
        prompt: "Write `barbieGreeting(name, career)` returning `\"Hi, I'm [name]! I'm a [career] Barbie.\"` via template literal. Log with `barbieGreeting('Barbie', 'Astronaut')`.",
        hint: "Backtick template with `${}` for name and career.",
        solution: `function barbieGreeting(name, career) {\n  return \`Hi, I'm \${name}! I'm a \${career} Barbie.\`;\n}\nconsole.log(barbieGreeting('Barbie', 'Astronaut'));`,
        starterCode: `function barbieGreeting(name, career) {\n  return \`Hi, I'm \${___}! I'm a \${___} Barbie.\`;\n}\nconsole.log(barbieGreeting('Barbie', 'Astronaut'));`,
        testCases: [{ input: "Barbie,Astronaut", expected: "Hi, I'm Barbie! I'm a Astronaut Barbie.", description: "Barbie career greeting" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "ba-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Ken is organising the Barbieland rollerblading league. Only Barbies with a happiness score above 8 qualify.",
        prompt: "Given `const barbies = [{name:'Barbie',happiness:10},{name:'Weird Barbie',happiness:7},{name:'President Barbie',happiness:9},{name:'Mermaid Barbie',happiness:6}]`, filter `happiness > 8` and log their names.",
        hint: "`.filter(b => b.happiness > 8).map(b => b.name)`",
        solution: `const barbies = [{name:'Barbie',happiness:10},{name:'Weird Barbie',happiness:7},{name:'President Barbie',happiness:9},{name:'Mermaid Barbie',happiness:6}];\nconst happy = barbies.filter(b => b.happiness > 8).map(b => b.name);\nconsole.log(happy);`,
        starterCode: `const barbies = [{name:'Barbie',happiness:10},{name:'Weird Barbie',happiness:7},{name:'President Barbie',happiness:9},{name:'Mermaid Barbie',happiness:6}];\nconst happy = barbies.filter(b => b.happiness > ___).map(b => b.name);\nconsole.log(happy);`,
        testCases: [{ input: "", expected: "[ 'Barbie', 'President Barbie' ]", description: "Happiest Barbies" }],
        conceptKeywords: ["filter", "map", "happiness", "=>"],
      },
      {
        id: "ba-js-final-3",
        concept: "Objects",
        narrative: "Ken needs his Barbieland ID card — a complete profile object.",
        prompt: "Create `const ken = { name: 'Ken', job: 'Beach', kenough: true, horses: true }`. Log `ken.job` and `ken.kenough`.",
        hint: "Object literal, dot notation to access properties.",
        solution: `const ken = { name: 'Ken', job: 'Beach', kenough: true, horses: true };\nconsole.log(ken.job);\nconsole.log(ken.kenough);`,
        starterCode: `const ken = { name: 'Ken', job: ___, kenough: ___, horses: true };\nconsole.log(ken.job);\nconsole.log(ken.kenough);`,
        testCases: [{ input: "", expected: "Beach\ntrue", description: "Ken's job and kenough status" }],
        conceptKeywords: ["const", "job", "kenough", "console.log"],
      },
      {
        id: "ba-js-final-4",
        concept: ".map()",
        narrative: "Barbie is converting her outfit collection names to uppercase for the fashion show catalogue.",
        prompt: "Given `const outfits = ['pink gown', 'space suit', 'doctor coat', 'cowgirl hat']`, use `.map()` to uppercase all. Log the result.",
        hint: "`.map(o => o.toUpperCase())`",
        solution: `const outfits = ['pink gown', 'space suit', 'doctor coat', 'cowgirl hat'];\nconst catalogue = outfits.map(o => o.toUpperCase());\nconsole.log(catalogue);`,
        starterCode: `const outfits = ['pink gown', 'space suit', 'doctor coat', 'cowgirl hat'];\nconst catalogue = outfits.map(o => o.___());\nconsole.log(catalogue);`,
        testCases: [{ input: "", expected: "[ 'PINK GOWN', 'SPACE SUIT', 'DOCTOR COAT', 'COWGIRL HAT' ]", description: "Uppercased outfit names" }],
        conceptKeywords: ["map", "toUpperCase", "=>"],
      },
      {
        id: "ba-js-final-5",
        concept: ".reduce()",
        narrative: "Barbie has been calculating her Dreamhouse renovation costs. Total up all the expenses.",
        prompt: "Given `const costs = [15000, 8000, 22000, 5500, 11000]`, use `.reduce()` to sum them. Log the total.",
        hint: "`.reduce((acc, c) => acc + c, 0)`",
        solution: `const costs = [15000, 8000, 22000, 5500, 11000];\nconst total = costs.reduce((acc, c) => acc + c, 0);\nconsole.log(total);`,
        starterCode: `const costs = [15000, 8000, 22000, 5500, 11000];\nconst total = costs.reduce((acc, c) => acc + c, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "61500", description: "Total renovation costs" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── Sex and the City ─────────────────────────────────────────────────────────
  "sex-and-the-city-javascript": {
    id: "sc-js-final",
    themeId: "sex-and-the-city",
    languageId: "javascript",
    themedTitle: "Carrie's Ultimate Column",
    introNarrative:
      "I couldn't help but wonder... can you code? Carrie has set five JavaScript challenges before she'll file her column. Grab a cosmo. It's time to find out if you're a Manolo or a sneaker.",
    questions: [
      {
        id: "sc-js-final-1",
        concept: "Template Literals",
        narrative: "Carrie opens every column with a rhetorical question. Generate the headline dynamically.",
        prompt: "Write `columnOpener(topic, city)` returning `\"In [city], I couldn't help but wonder about [topic].\"` via template literal. Log with `columnOpener('love', 'New York')`.",
        hint: "Backtick template with `${city}` and `${topic}`.",
        solution: `function columnOpener(topic, city) {\n  return \`In \${city}, I couldn't help but wonder about \${topic}.\`;\n}\nconsole.log(columnOpener('love', 'New York'));`,
        starterCode: `function columnOpener(topic, city) {\n  return \`In \${___}, I couldn't help but wonder about \${___}.\`;\n}\nconsole.log(columnOpener('love', 'New York'));`,
        testCases: [{ input: "love,New York", expected: "In New York, I couldn't help but wonder about love.", description: "Column opener" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "sc-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Miranda is reviewing her client list. Only those with a case value above $50,000 get priority attention.",
        prompt: "Given `const clients = [{name:'Big',caseValue:120000},{name:'Aidan',caseValue:35000},{name:'Berger',caseValue:55000},{name:'Petrovsky',caseValue:28000}]`, filter `caseValue > 50000` and log their names.",
        hint: "`.filter(c => c.caseValue > 50000).map(c => c.name)`",
        solution: `const clients = [{name:'Big',caseValue:120000},{name:'Aidan',caseValue:35000},{name:'Berger',caseValue:55000},{name:'Petrovsky',caseValue:28000}];\nconst priority = clients.filter(c => c.caseValue > 50000).map(c => c.name);\nconsole.log(priority);`,
        starterCode: `const clients = [{name:'Big',caseValue:120000},{name:'Aidan',caseValue:35000},{name:'Berger',caseValue:55000},{name:'Petrovsky',caseValue:28000}];\nconst priority = clients.filter(c => c.caseValue > ___).map(c => c.name);\nconsole.log(priority);`,
        testCases: [{ input: "", expected: "[ 'Big', 'Berger' ]", description: "Priority clients" }],
        conceptKeywords: ["filter", "map", "caseValue", "=>"],
      },
      {
        id: "sc-js-final-3",
        concept: "Objects",
        narrative: "Charlotte is cataloguing Carrie's shoe collection for insurance purposes.",
        prompt: "Create `const shoe = { brand: 'Manolo Blahnik', style: 'Hangisi', heel: 3.5, priceless: true }`. Log `shoe.brand` and `shoe.heel`.",
        hint: "Object literal with dot notation to access.",
        solution: `const shoe = { brand: 'Manolo Blahnik', style: 'Hangisi', heel: 3.5, priceless: true };\nconsole.log(shoe.brand);\nconsole.log(shoe.heel);`,
        starterCode: `const shoe = { brand: ___, style: 'Hangisi', heel: ___, priceless: true };\nconsole.log(shoe.brand);\nconsole.log(shoe.heel);`,
        testCases: [{ input: "", expected: "Manolo Blahnik\n3.5", description: "Brand and heel height" }],
        conceptKeywords: ["const", "brand", "heel", "console.log"],
      },
      {
        id: "sc-js-final-4",
        concept: ".map()",
        narrative: "Samantha is formatting her PR client roster for the agency letterhead — all names must be uppercase.",
        prompt: "Given `const clients = ['Smith PR', 'Jones Media', 'Hudson Events', 'Park Avenue PR']`, use `.map()` to uppercase all. Log the result.",
        hint: "`.map(c => c.toUpperCase())`",
        solution: `const clients = ['Smith PR', 'Jones Media', 'Hudson Events', 'Park Avenue PR'];\nconst letterhead = clients.map(c => c.toUpperCase());\nconsole.log(letterhead);`,
        starterCode: `const clients = ['Smith PR', 'Jones Media', 'Hudson Events', 'Park Avenue PR'];\nconst letterhead = clients.map(c => c.___());\nconsole.log(letterhead);`,
        testCases: [{ input: "", expected: "[ 'SMITH PR', 'JONES MEDIA', 'HUDSON EVENTS', 'PARK AVENUE PR' ]", description: "Uppercased PR clients" }],
        conceptKeywords: ["map", "toUpperCase", "=>"],
      },
      {
        id: "sc-js-final-5",
        concept: ".reduce()",
        narrative: "Carrie is tallying up what she spent on shoes this season — the number is both horrifying and glorious.",
        prompt: "Given `const shoeSpend = [895, 1200, 450, 780, 1650]`, use `.reduce()` to total the spending. Log it.",
        hint: "`.reduce((acc, s) => acc + s, 0)`",
        solution: `const shoeSpend = [895, 1200, 450, 780, 1650];\nconst total = shoeSpend.reduce((acc, s) => acc + s, 0);\nconsole.log(total);`,
        starterCode: `const shoeSpend = [895, 1200, 450, 780, 1650];\nconst total = shoeSpend.reduce((acc, s) => acc + s, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "4975", description: "Total shoe spending" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },

  // ── The Sopranos ─────────────────────────────────────────────────────────────
  "sopranos-javascript": {
    id: "sp-js-final",
    themeId: "sopranos",
    languageId: "javascript",
    themedTitle: "The Family Business Exam",
    introNarrative:
      "Tony Soprano has taken an interest in this coding thing. He's heard the 'information superhighway' is good for business. Five challenges. You pass, you're with us. You don't... well, the ducks are very fond of the pool.",
    questions: [
      {
        id: "sp-js-final-1",
        concept: "Template Literals",
        narrative: "Christopher is writing up the weekly earnings report. Tony likes it formatted a specific way.",
        prompt: "Write `weeklyReport(name, amount)` returning `\"[name] brought in $[amount] this week.\"` via template literal. Log with `weeklyReport('Paulie', 45000)`.",
        hint: "Template literal with `${}` for name and amount.",
        solution: `function weeklyReport(name, amount) {\n  return \`\${name} brought in $\${amount} this week.\`;\n}\nconsole.log(weeklyReport('Paulie', 45000));`,
        starterCode: `function weeklyReport(name, amount) {\n  return \`\${___} brought in $\${___} this week.\`;\n}\nconsole.log(weeklyReport('Paulie', 45000));`,
        testCases: [{ input: "Paulie,45000", expected: "Paulie brought in $45000 this week.", description: "Weekly earnings report" }],
        conceptKeywords: ["function", "return", "`", "${"],
      },
      {
        id: "sp-js-final-2",
        concept: "Arrays & .filter()",
        narrative: "Bobby needs to identify which crew members are bringing in enough to cover their nut this week.",
        prompt: "Given `const crew = [{name:'Paulie',earnings:45000},{name:'Christopher',earnings:22000},{name:'Silvio',earnings:55000},{name:'Bobby',earnings:18000}]`, filter `earnings >= 30000` and log their names.",
        hint: "`.filter(m => m.earnings >= 30000).map(m => m.name)`",
        solution: `const crew = [{name:'Paulie',earnings:45000},{name:'Christopher',earnings:22000},{name:'Silvio',earnings:55000},{name:'Bobby',earnings:18000}];\nconst producers = crew.filter(m => m.earnings >= 30000).map(m => m.name);\nconsole.log(producers);`,
        starterCode: `const crew = [{name:'Paulie',earnings:45000},{name:'Christopher',earnings:22000},{name:'Silvio',earnings:55000},{name:'Bobby',earnings:18000}];\nconst producers = crew.filter(m => m.earnings >= ___).map(m => m.name);\nconsole.log(producers);`,
        testCases: [{ input: "", expected: "[ 'Paulie', 'Silvio' ]", description: "Top earners" }],
        conceptKeywords: ["filter", "map", "earnings", "=>"],
      },
      {
        id: "sp-js-final-3",
        concept: "Objects",
        narrative: "Dr. Melfi needs Tony's complete profile on file for their sessions.",
        prompt: "Create `const tony = { name: 'Tony Soprano', business: 'waste management', ducks: true, sessions: 83 }`. Log `tony.business` and `tony.sessions`.",
        hint: "Object literal, dot notation.",
        solution: `const tony = { name: 'Tony Soprano', business: 'waste management', ducks: true, sessions: 83 };\nconsole.log(tony.business);\nconsole.log(tony.sessions);`,
        starterCode: `const tony = { name: 'Tony Soprano', business: ___, ducks: true, sessions: ___ };\nconsole.log(tony.business);\nconsole.log(tony.sessions);`,
        testCases: [{ input: "", expected: "waste management\n83", description: "Tony's business and sessions" }],
        conceptKeywords: ["const", "business", "sessions", "console.log"],
      },
      {
        id: "sp-js-final-4",
        concept: ".map()",
        narrative: "Silvio is formatting the Bada Bing's performer lineup for the printed schedule — all names in uppercase.",
        prompt: "Given `const performers = ['Bambi', 'Crystal', 'Candy', 'Diamond']`, use `.map()` to uppercase all. Log the result.",
        hint: "`.map(p => p.toUpperCase())`",
        solution: `const performers = ['Bambi', 'Crystal', 'Candy', 'Diamond'];\nconst schedule = performers.map(p => p.toUpperCase());\nconsole.log(schedule);`,
        starterCode: `const performers = ['Bambi', 'Crystal', 'Candy', 'Diamond'];\nconst schedule = performers.map(p => p.___());\nconsole.log(schedule);`,
        testCases: [{ input: "", expected: "[ 'BAMBI', 'CRYSTAL', 'CANDY', 'DIAMOND' ]", description: "Uppercase performer names" }],
        conceptKeywords: ["map", "toUpperCase", "=>"],
      },
      {
        id: "sp-js-final-5",
        concept: ".reduce()",
        narrative: "Carmela is reconciling the family finances. Add up all of Tony's \"consulting\" income for the quarter.",
        prompt: "Given `const income = [85000, 120000, 67000, 95000, 110000]`, use `.reduce()` to total it. Log the result.",
        hint: "`.reduce((acc, n) => acc + n, 0)`",
        solution: `const income = [85000, 120000, 67000, 95000, 110000];\nconst total = income.reduce((acc, n) => acc + n, 0);\nconsole.log(total);`,
        starterCode: `const income = [85000, 120000, 67000, 95000, 110000];\nconst total = income.reduce((acc, n) => acc + n, ___);\nconsole.log(total);`,
        testCases: [{ input: "", expected: "477000", description: "Total consulting income" }],
        conceptKeywords: ["reduce", "acc", "0"],
      },
    ],
  },
};
